(api:"/servicePrincipals"):operation5223,
(api:"/servicePrincipals/{servicePrincipal-id}",servicePrincipalid: string):operation5224,
(api:"/servicePrincipals/{servicePrincipal-id}/appRoleAssignedTo",servicePrincipalid: string):operation5225,
(api:"/servicePrincipals/{servicePrincipal-id}/appRoleAssignedTo/{appRoleAssignment-id}",servicePrincipalid: string,appRoleAssignmentid: string):operation5226,
(api:"/servicePrincipals/{servicePrincipal-id}/appRoleAssignedTo/$count",servicePrincipalid: string):operation5227,
(api:"/servicePrincipals/{servicePrincipal-id}/appRoleAssignments",servicePrincipalid: string):operation5228,
(api:"/servicePrincipals/{servicePrincipal-id}/appRoleAssignments/{appRoleAssignment-id}",servicePrincipalid: string,appRoleAssignmentid: string):operation5229,
(api:"/servicePrincipals/{servicePrincipal-id}/appRoleAssignments/$count",servicePrincipalid: string):operation5230,
(api:"/servicePrincipals/{servicePrincipal-id}/claimsMappingPolicies",servicePrincipalid: string):operation5231,
(api:"/servicePrincipals/{servicePrincipal-id}/claimsMappingPolicies/{claimsMappingPolicy-id}/$ref",servicePrincipalid: string,claimsMappingPolicyid: string):operation5232,
(api:"/servicePrincipals/{servicePrincipal-id}/claimsMappingPolicies/$count",servicePrincipalid: string):operation5233,
(api:"/servicePrincipals/{servicePrincipal-id}/claimsMappingPolicies/$ref",servicePrincipalid: string):operation5234,
(api:"/servicePrincipals/{servicePrincipal-id}/createdObjects",servicePrincipalid: string):operation5235,
(api:"/servicePrincipals/{servicePrincipal-id}/createdObjects/{directoryObject-id}",servicePrincipalid: string,directoryObjectid: string):operation5236,
(api:"/servicePrincipals/{servicePrincipal-id}/createdObjects/{directoryObject-id}/microsoft.graph.servicePrincipal",servicePrincipalid: string,directoryObjectid: string):operation5237,
(api:"/servicePrincipals/{servicePrincipal-id}/createdObjects/$count",servicePrincipalid: string):operation5238,
(api:"/servicePrincipals/{servicePrincipal-id}/createdObjects/microsoft.graph.servicePrincipal",servicePrincipalid: string):operation5239,
(api:"/servicePrincipals/{servicePrincipal-id}/createdObjects/microsoft.graph.servicePrincipal/$count",servicePrincipalid: string):operation5240,
(api:"/servicePrincipals/{servicePrincipal-id}/delegatedPermissionClassifications",servicePrincipalid: string):operation5241,
(api:"/servicePrincipals/{servicePrincipal-id}/delegatedPermissionClassifications/{delegatedPermissionClassification-id}",servicePrincipalid: string,delegatedPermissionClassificationid: string):operation5242,
(api:"/servicePrincipals/{servicePrincipal-id}/delegatedPermissionClassifications/$count",servicePrincipalid: string):operation5243,
(api:"/servicePrincipals/{servicePrincipal-id}/endpoints",servicePrincipalid: string):operation5244,
(api:"/servicePrincipals/{servicePrincipal-id}/endpoints/{endpoint-id}",servicePrincipalid: string,endpointid: string):operation5245,
(api:"/servicePrincipals/{servicePrincipal-id}/endpoints/$count",servicePrincipalid: string):operation5246,
(api:"/servicePrincipals/{servicePrincipal-id}/federatedIdentityCredentials",servicePrincipalid: string):operation5247,
(api:"/servicePrincipals/{servicePrincipal-id}/federatedIdentityCredentials/{federatedIdentityCredential-id}",servicePrincipalid: string,federatedIdentityCredentialid: string):operation5248,
(api:"/servicePrincipals/{servicePrincipal-id}/federatedIdentityCredentials/$count",servicePrincipalid: string):operation5249,
(api:"/servicePrincipals/{servicePrincipal-id}/homeRealmDiscoveryPolicies",servicePrincipalid: string):operation5250,
(api:"/servicePrincipals/{servicePrincipal-id}/homeRealmDiscoveryPolicies/{homeRealmDiscoveryPolicy-id}/$ref",servicePrincipalid: string,homeRealmDiscoveryPolicyid: string):operation5251,
(api:"/servicePrincipals/{servicePrincipal-id}/homeRealmDiscoveryPolicies/$count",servicePrincipalid: string):operation5252,
(api:"/servicePrincipals/{servicePrincipal-id}/homeRealmDiscoveryPolicies/$ref",servicePrincipalid: string):operation5253,
(api:"/servicePrincipals/{servicePrincipal-id}/memberOf",servicePrincipalid: string):operation5254,
(api:"/servicePrincipals/{servicePrincipal-id}/memberOf/{directoryObject-id}",servicePrincipalid: string,directoryObjectid: string):operation5255,
(api:"/servicePrincipals/{servicePrincipal-id}/memberOf/{directoryObject-id}/microsoft.graph.application",servicePrincipalid: string,directoryObjectid: string):operation5256,
(api:"/servicePrincipals/{servicePrincipal-id}/memberOf/{directoryObject-id}/microsoft.graph.device",servicePrincipalid: string,directoryObjectid: string):operation5257,
(api:"/servicePrincipals/{servicePrincipal-id}/memberOf/{directoryObject-id}/microsoft.graph.group",servicePrincipalid: string,directoryObjectid: string):operation5258,
(api:"/servicePrincipals/{servicePrincipal-id}/memberOf/{directoryObject-id}/microsoft.graph.orgContact",servicePrincipalid: string,directoryObjectid: string):operation5259,
(api:"/servicePrincipals/{servicePrincipal-id}/memberOf/{directoryObject-id}/microsoft.graph.servicePrincipal",servicePrincipalid: string,directoryObjectid: string):operation5260,
(api:"/servicePrincipals/{servicePrincipal-id}/memberOf/{directoryObject-id}/microsoft.graph.user",servicePrincipalid: string,directoryObjectid: string):operation5261,
(api:"/servicePrincipals/{servicePrincipal-id}/memberOf/$count",servicePrincipalid: string):operation5262,
(api:"/servicePrincipals/{servicePrincipal-id}/memberOf/microsoft.graph.application",servicePrincipalid: string):operation5263,
(api:"/servicePrincipals/{servicePrincipal-id}/memberOf/microsoft.graph.application/$count",servicePrincipalid: string):operation5264,
(api:"/servicePrincipals/{servicePrincipal-id}/memberOf/microsoft.graph.device",servicePrincipalid: string):operation5265,
(api:"/servicePrincipals/{servicePrincipal-id}/memberOf/microsoft.graph.device/$count",servicePrincipalid: string):operation5266,
(api:"/servicePrincipals/{servicePrincipal-id}/memberOf/microsoft.graph.group",servicePrincipalid: string):operation5267,
(api:"/servicePrincipals/{servicePrincipal-id}/memberOf/microsoft.graph.group/$count",servicePrincipalid: string):operation5268,
(api:"/servicePrincipals/{servicePrincipal-id}/memberOf/microsoft.graph.orgContact",servicePrincipalid: string):operation5269,
(api:"/servicePrincipals/{servicePrincipal-id}/memberOf/microsoft.graph.orgContact/$count",servicePrincipalid: string):operation5270,
(api:"/servicePrincipals/{servicePrincipal-id}/memberOf/microsoft.graph.servicePrincipal",servicePrincipalid: string):operation5271,
(api:"/servicePrincipals/{servicePrincipal-id}/memberOf/microsoft.graph.servicePrincipal/$count",servicePrincipalid: string):operation5272,
(api:"/servicePrincipals/{servicePrincipal-id}/memberOf/microsoft.graph.user",servicePrincipalid: string):operation5273,
(api:"/servicePrincipals/{servicePrincipal-id}/memberOf/microsoft.graph.user/$count",servicePrincipalid: string):operation5274,
(api:"/servicePrincipals/{servicePrincipal-id}/microsoft.graph.addKey",servicePrincipalid: string):operation5275,
(api:"/servicePrincipals/{servicePrincipal-id}/microsoft.graph.addPassword",servicePrincipalid: string):operation5276,
(api:"/servicePrincipals/{servicePrincipal-id}/microsoft.graph.addTokenSigningCertificate",servicePrincipalid: string):operation5277,
(api:"/servicePrincipals/{servicePrincipal-id}/microsoft.graph.checkMemberGroups",servicePrincipalid: string):operation5278,
(api:"/servicePrincipals/{servicePrincipal-id}/microsoft.graph.checkMemberObjects",servicePrincipalid: string):operation5279,
(api:"/servicePrincipals/{servicePrincipal-id}/microsoft.graph.getMemberGroups",servicePrincipalid: string):operation5280,
(api:"/servicePrincipals/{servicePrincipal-id}/microsoft.graph.getMemberObjects",servicePrincipalid: string):operation5281,
(api:"/servicePrincipals/{servicePrincipal-id}/microsoft.graph.removeKey",servicePrincipalid: string):operation5282,
(api:"/servicePrincipals/{servicePrincipal-id}/microsoft.graph.removePassword",servicePrincipalid: string):operation5283,
(api:"/servicePrincipals/{servicePrincipal-id}/microsoft.graph.restore",servicePrincipalid: string):operation5284,
(api:"/servicePrincipals/{servicePrincipal-id}/oauth2PermissionGrants",servicePrincipalid: string):operation5285,
(api:"/servicePrincipals/{servicePrincipal-id}/oauth2PermissionGrants/{oAuth2PermissionGrant-id}",servicePrincipalid: string,oAuth2PermissionGrantid: string):operation5286,
(api:"/servicePrincipals/{servicePrincipal-id}/oauth2PermissionGrants/$count",servicePrincipalid: string):operation5287,
(api:"/servicePrincipals/{servicePrincipal-id}/ownedObjects",servicePrincipalid: string):operation5288,
(api:"/servicePrincipals/{servicePrincipal-id}/ownedObjects/{directoryObject-id}",servicePrincipalid: string,directoryObjectid: string):operation5289,
(api:"/servicePrincipals/{servicePrincipal-id}/ownedObjects/{directoryObject-id}/microsoft.graph.application",servicePrincipalid: string,directoryObjectid: string):operation5290,
(api:"/servicePrincipals/{servicePrincipal-id}/ownedObjects/{directoryObject-id}/microsoft.graph.appRoleAssignment",servicePrincipalid: string,directoryObjectid: string):operation5291,
(api:"/servicePrincipals/{servicePrincipal-id}/ownedObjects/{directoryObject-id}/microsoft.graph.endpoint",servicePrincipalid: string,directoryObjectid: string):operation5292,
(api:"/servicePrincipals/{servicePrincipal-id}/ownedObjects/{directoryObject-id}/microsoft.graph.group",servicePrincipalid: string,directoryObjectid: string):operation5293,
(api:"/servicePrincipals/{servicePrincipal-id}/ownedObjects/{directoryObject-id}/microsoft.graph.servicePrincipal",servicePrincipalid: string,directoryObjectid: string):operation5294,
(api:"/servicePrincipals/{servicePrincipal-id}/ownedObjects/$count",servicePrincipalid: string):operation5295,
(api:"/servicePrincipals/{servicePrincipal-id}/ownedObjects/microsoft.graph.application",servicePrincipalid: string):operation5296,
(api:"/servicePrincipals/{servicePrincipal-id}/ownedObjects/microsoft.graph.application/$count",servicePrincipalid: string):operation5297,
(api:"/servicePrincipals/{servicePrincipal-id}/ownedObjects/microsoft.graph.appRoleAssignment",servicePrincipalid: string):operation5298,
(api:"/servicePrincipals/{servicePrincipal-id}/ownedObjects/microsoft.graph.appRoleAssignment/$count",servicePrincipalid: string):operation5299,
(api:"/servicePrincipals/{servicePrincipal-id}/ownedObjects/microsoft.graph.endpoint",servicePrincipalid: string):operation5300,
(api:"/servicePrincipals/{servicePrincipal-id}/ownedObjects/microsoft.graph.endpoint/$count",servicePrincipalid: string):operation5301,
(api:"/servicePrincipals/{servicePrincipal-id}/ownedObjects/microsoft.graph.group",servicePrincipalid: string):operation5302,
(api:"/servicePrincipals/{servicePrincipal-id}/ownedObjects/microsoft.graph.group/$count",servicePrincipalid: string):operation5303,
(api:"/servicePrincipals/{servicePrincipal-id}/ownedObjects/microsoft.graph.servicePrincipal",servicePrincipalid: string):operation5304,
(api:"/servicePrincipals/{servicePrincipal-id}/ownedObjects/microsoft.graph.servicePrincipal/$count",servicePrincipalid: string):operation5305,
(api:"/servicePrincipals/{servicePrincipal-id}/owners",servicePrincipalid: string):operation5306,
(api:"/servicePrincipals/{servicePrincipal-id}/owners/{directoryObject-id}/$ref",servicePrincipalid: string,directoryObjectid: string):operation5307,
(api:"/servicePrincipals/{servicePrincipal-id}/owners/{directoryObject-id}/microsoft.graph.appRoleAssignment",servicePrincipalid: string,directoryObjectid: string):operation5308,
(api:"/servicePrincipals/{servicePrincipal-id}/owners/{directoryObject-id}/microsoft.graph.endpoint",servicePrincipalid: string,directoryObjectid: string):operation5309,
(api:"/servicePrincipals/{servicePrincipal-id}/owners/{directoryObject-id}/microsoft.graph.servicePrincipal",servicePrincipalid: string,directoryObjectid: string):operation5310,
(api:"/servicePrincipals/{servicePrincipal-id}/owners/{directoryObject-id}/microsoft.graph.user",servicePrincipalid: string,directoryObjectid: string):operation5311,
(api:"/servicePrincipals/{servicePrincipal-id}/owners/$count",servicePrincipalid: string):operation5312,
(api:"/servicePrincipals/{servicePrincipal-id}/owners/$ref",servicePrincipalid: string):operation5313,
(api:"/servicePrincipals/{servicePrincipal-id}/owners/microsoft.graph.appRoleAssignment",servicePrincipalid: string):operation5314,
(api:"/servicePrincipals/{servicePrincipal-id}/owners/microsoft.graph.appRoleAssignment/$count",servicePrincipalid: string):operation5315,
(api:"/servicePrincipals/{servicePrincipal-id}/owners/microsoft.graph.endpoint",servicePrincipalid: string):operation5316,
(api:"/servicePrincipals/{servicePrincipal-id}/owners/microsoft.graph.endpoint/$count",servicePrincipalid: string):operation5317,
(api:"/servicePrincipals/{servicePrincipal-id}/owners/microsoft.graph.servicePrincipal",servicePrincipalid: string):operation5318,
(api:"/servicePrincipals/{servicePrincipal-id}/owners/microsoft.graph.servicePrincipal/$count",servicePrincipalid: string):operation5319,
(api:"/servicePrincipals/{servicePrincipal-id}/owners/microsoft.graph.user",servicePrincipalid: string):operation5320,
(api:"/servicePrincipals/{servicePrincipal-id}/owners/microsoft.graph.user/$count",servicePrincipalid: string):operation5321,
(api:"/servicePrincipals/{servicePrincipal-id}/tokenIssuancePolicies",servicePrincipalid: string):operation5322,
(api:"/servicePrincipals/{servicePrincipal-id}/tokenIssuancePolicies/{tokenIssuancePolicy-id}",servicePrincipalid: string,tokenIssuancePolicyid: string):operation5323,
(api:"/servicePrincipals/{servicePrincipal-id}/tokenIssuancePolicies/$count",servicePrincipalid: string):operation5324,
(api:"/servicePrincipals/{servicePrincipal-id}/tokenLifetimePolicies",servicePrincipalid: string):operation5325,
(api:"/servicePrincipals/{servicePrincipal-id}/tokenLifetimePolicies/{tokenLifetimePolicy-id}",servicePrincipalid: string,tokenLifetimePolicyid: string):operation5326,
(api:"/servicePrincipals/{servicePrincipal-id}/tokenLifetimePolicies/$count",servicePrincipalid: string):operation5327,
(api:"/servicePrincipals/{servicePrincipal-id}/transitiveMemberOf",servicePrincipalid: string):operation5328,
(api:"/servicePrincipals/{servicePrincipal-id}/transitiveMemberOf/{directoryObject-id}",servicePrincipalid: string,directoryObjectid: string):operation5329,
(api:"/servicePrincipals/{servicePrincipal-id}/transitiveMemberOf/{directoryObject-id}/microsoft.graph.application",servicePrincipalid: string,directoryObjectid: string):operation5330,
(api:"/servicePrincipals/{servicePrincipal-id}/transitiveMemberOf/{directoryObject-id}/microsoft.graph.device",servicePrincipalid: string,directoryObjectid: string):operation5331,
(api:"/servicePrincipals/{servicePrincipal-id}/transitiveMemberOf/{directoryObject-id}/microsoft.graph.group",servicePrincipalid: string,directoryObjectid: string):operation5332,
(api:"/servicePrincipals/{servicePrincipal-id}/transitiveMemberOf/{directoryObject-id}/microsoft.graph.orgContact",servicePrincipalid: string,directoryObjectid: string):operation5333,
(api:"/servicePrincipals/{servicePrincipal-id}/transitiveMemberOf/{directoryObject-id}/microsoft.graph.servicePrincipal",servicePrincipalid: string,directoryObjectid: string):operation5334,
(api:"/servicePrincipals/{servicePrincipal-id}/transitiveMemberOf/{directoryObject-id}/microsoft.graph.user",servicePrincipalid: string,directoryObjectid: string):operation5335,
(api:"/servicePrincipals/{servicePrincipal-id}/transitiveMemberOf/$count",servicePrincipalid: string):operation5336,
(api:"/servicePrincipals/{servicePrincipal-id}/transitiveMemberOf/microsoft.graph.application",servicePrincipalid: string):operation5337,
(api:"/servicePrincipals/{servicePrincipal-id}/transitiveMemberOf/microsoft.graph.application/$count",servicePrincipalid: string):operation5338,
(api:"/servicePrincipals/{servicePrincipal-id}/transitiveMemberOf/microsoft.graph.device",servicePrincipalid: string):operation5339,
(api:"/servicePrincipals/{servicePrincipal-id}/transitiveMemberOf/microsoft.graph.device/$count",servicePrincipalid: string):operation5340,
(api:"/servicePrincipals/{servicePrincipal-id}/transitiveMemberOf/microsoft.graph.group",servicePrincipalid: string):operation5341,
(api:"/servicePrincipals/{servicePrincipal-id}/transitiveMemberOf/microsoft.graph.group/$count",servicePrincipalid: string):operation5342,
(api:"/servicePrincipals/{servicePrincipal-id}/transitiveMemberOf/microsoft.graph.orgContact",servicePrincipalid: string):operation5343,
(api:"/servicePrincipals/{servicePrincipal-id}/transitiveMemberOf/microsoft.graph.orgContact/$count",servicePrincipalid: string):operation5344,
(api:"/servicePrincipals/{servicePrincipal-id}/transitiveMemberOf/microsoft.graph.servicePrincipal",servicePrincipalid: string):operation5345,
(api:"/servicePrincipals/{servicePrincipal-id}/transitiveMemberOf/microsoft.graph.servicePrincipal/$count",servicePrincipalid: string):operation5346,
(api:"/servicePrincipals/{servicePrincipal-id}/transitiveMemberOf/microsoft.graph.user",servicePrincipalid: string):operation5347,
(api:"/servicePrincipals/{servicePrincipal-id}/transitiveMemberOf/microsoft.graph.user/$count",servicePrincipalid: string):operation5348,
(api:"/servicePrincipals/$count"):operation5349,
(api:"/servicePrincipals/microsoft.graph.delta()"):operation5350,
(api:"/servicePrincipals/microsoft.graph.getAvailableExtensionProperties"):operation5351,
(api:"/servicePrincipals/microsoft.graph.getByIds"):operation5352,
(api:"/servicePrincipals/microsoft.graph.validateProperties"):operation5353,