(api:"/users/{user-id}/calendar/events",userid: string):operation6412,
    (api:"/users/{user-id}/calendar/events/{event-id}",userid: string,eventid: string):operation6413,
    (api:"/users/{user-id}/calendar/events/{event-id}/attachments",userid: string,eventid: string):operation6414,
    (api:"/users/{user-id}/calendar/events/{event-id}/attachments/{attachment-id}",userid: string,eventid: string,attachmentid: string):operation6415,
    (api:"/users/{user-id}/calendar/events/{event-id}/attachments/$count",userid: string,eventid: string):operation6416,
    (api:"/users/{user-id}/calendar/events/{event-id}/attachments/microsoft.graph.createUploadSession",userid: string,eventid: string):operation6417,
    (api:"/users/{user-id}/calendar/events/{event-id}/calendar",userid: string,eventid: string):operation6418,
    (api:"/users/{user-id}/calendar/events/{event-id}/extensions",userid: string,eventid: string):operation6419,
    (api:"/users/{user-id}/calendar/events/{event-id}/extensions/{extension-id}",userid: string,eventid: string,extensionid: string):operation6420,
    (api:"/users/{user-id}/calendar/events/{event-id}/extensions/$count",userid: string,eventid: string):operation6421,
    (api:"/users/{user-id}/calendar/events/{event-id}/instances",userid: string,eventid: string):operation6422,
    (api:"/users/{user-id}/calendar/events/{event-id}/instances/{event-id1}",userid: string,eventid: string,eventid1: string):operation6423,
    (api:"/users/{user-id}/calendar/events/{event-id}/instances/{event-id1}/attachments",userid: string,eventid: string,eventid1: string):operation6424,
    (api:"/users/{user-id}/calendar/events/{event-id}/instances/{event-id1}/attachments/{attachment-id}",userid: string,eventid: string,eventid1: string,attachmentid: string):operation6425,
    (api:"/users/{user-id}/calendar/events/{event-id}/instances/{event-id1}/attachments/$count",userid: string,eventid: string,eventid1: string):operation6426,
    (api:"/users/{user-id}/calendar/events/{event-id}/instances/{event-id1}/attachments/microsoft.graph.createUploadSession",userid: string,eventid: string,eventid1: string):operation6427,
    (api:"/users/{user-id}/calendar/events/{event-id}/instances/{event-id1}/calendar",userid: string,eventid: string,eventid1: string):operation6428,
    (api:"/users/{user-id}/calendar/events/{event-id}/instances/{event-id1}/extensions",userid: string,eventid: string,eventid1: string):operation6429,
    (api:"/users/{user-id}/calendar/events/{event-id}/instances/{event-id1}/extensions/{extension-id}",userid: string,eventid: string,eventid1: string,extensionid: string):operation6430,
    (api:"/users/{user-id}/calendar/events/{event-id}/instances/{event-id1}/extensions/$count",userid: string,eventid: string,eventid1: string):operation6431,
    (api:"/users/{user-id}/calendar/events/{event-id}/instances/{event-id1}/microsoft.graph.accept",userid: string,eventid: string,eventid1: string):operation6432,
    (api:"/users/{user-id}/calendar/events/{event-id}/instances/{event-id1}/microsoft.graph.cancel",userid: string,eventid: string,eventid1: string):operation6433,
    (api:"/users/{user-id}/calendar/events/{event-id}/instances/{event-id1}/microsoft.graph.decline",userid: string,eventid: string,eventid1: string):operation6434,
    (api:"/users/{user-id}/calendar/events/{event-id}/instances/{event-id1}/microsoft.graph.dismissReminder",userid: string,eventid: string,eventid1: string):operation6435,
    (api:"/users/{user-id}/calendar/events/{event-id}/instances/{event-id1}/microsoft.graph.forward",userid: string,eventid: string,eventid1: string):operation6436,
    (api:"/users/{user-id}/calendar/events/{event-id}/instances/{event-id1}/microsoft.graph.snoozeReminder",userid: string,eventid: string,eventid1: string):operation6437,
    (api:"/users/{user-id}/calendar/events/{event-id}/instances/{event-id1}/microsoft.graph.tentativelyAccept",userid: string,eventid: string,eventid1: string):operation6438,
    (api:"/users/{user-id}/calendar/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties",userid: string,eventid: string,eventid1: string):operation6439,
    (api:"/users/{user-id}/calendar/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}",userid: string,eventid: string,eventid1: string,multiValueLegacyExtendedPropertyid: string):operation6440,
    (api:"/users/{user-id}/calendar/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties/$count",userid: string,eventid: string,eventid1: string):operation6441,
    (api:"/users/{user-id}/calendar/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties",userid: string,eventid: string,eventid1: string):operation6442,
    (api:"/users/{user-id}/calendar/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}",userid: string,eventid: string,eventid1: string,singleValueLegacyExtendedPropertyid: string):operation6443,
    (api:"/users/{user-id}/calendar/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties/$count",userid: string,eventid: string,eventid1: string):operation6444,
    (api:"/users/{user-id}/calendar/events/{event-id}/instances/$count",userid: string,eventid: string):operation6445,
    (api:"/users/{user-id}/calendar/events/{event-id}/instances/microsoft.graph.delta()",userid: string,eventid: string):operation6446,
    (api:"/users/{user-id}/calendar/events/{event-id}/microsoft.graph.accept",userid: string,eventid: string):operation6447,
    (api:"/users/{user-id}/calendar/events/{event-id}/microsoft.graph.cancel",userid: string,eventid: string):operation6448,
    (api:"/users/{user-id}/calendar/events/{event-id}/microsoft.graph.decline",userid: string,eventid: string):operation6449,
    (api:"/users/{user-id}/calendar/events/{event-id}/microsoft.graph.dismissReminder",userid: string,eventid: string):operation6450,
    (api:"/users/{user-id}/calendar/events/{event-id}/microsoft.graph.forward",userid: string,eventid: string):operation6451,
    (api:"/users/{user-id}/calendar/events/{event-id}/microsoft.graph.snoozeReminder",userid: string,eventid: string):operation6452,
    (api:"/users/{user-id}/calendar/events/{event-id}/microsoft.graph.tentativelyAccept",userid: string,eventid: string):operation6453,
    (api:"/users/{user-id}/calendar/events/{event-id}/multiValueExtendedProperties",userid: string,eventid: string):operation6454,
    (api:"/users/{user-id}/calendar/events/{event-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}",userid: string,eventid: string,multiValueLegacyExtendedPropertyid: string):operation6455,
    (api:"/users/{user-id}/calendar/events/{event-id}/multiValueExtendedProperties/$count",userid: string,eventid: string):operation6456,
    (api:"/users/{user-id}/calendar/events/{event-id}/singleValueExtendedProperties",userid: string,eventid: string):operation6457,
    (api:"/users/{user-id}/calendar/events/{event-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}",userid: string,eventid: string,singleValueLegacyExtendedPropertyid: string):operation6458,
    (api:"/users/{user-id}/calendar/events/{event-id}/singleValueExtendedProperties/$count",userid: string,eventid: string):operation6459,
    (api:"/users/{user-id}/calendar/events/$count",userid: string):operation6460,
    (api:"/users/{user-id}/calendar/events/microsoft.graph.delta()",userid: string):operation6461,

    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events",userid: string,calendarGroupid: string,calendarid: string):operation6527,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}",userid: string,calendarGroupid: string,calendarid: string,eventid: string):operation6528,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/attachments",userid: string,calendarGroupid: string,calendarid: string,eventid: string):operation6529,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/attachments/{attachment-id}",userid: string,calendarGroupid: string,calendarid: string,eventid: string,attachmentid: string):operation6530,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/attachments/$count",userid: string,calendarGroupid: string,calendarid: string,eventid: string):operation6531,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/attachments/microsoft.graph.createUploadSession",userid: string,calendarGroupid: string,calendarid: string,eventid: string):operation6532,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/calendar",userid: string,calendarGroupid: string,calendarid: string,eventid: string):operation6533,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/extensions",userid: string,calendarGroupid: string,calendarid: string,eventid: string):operation6534,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/extensions/{extension-id}",userid: string,calendarGroupid: string,calendarid: string,eventid: string,extensionid: string):operation6535,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/extensions/$count",userid: string,calendarGroupid: string,calendarid: string,eventid: string):operation6536,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances",userid: string,calendarGroupid: string,calendarid: string,eventid: string):operation6537,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}",userid: string,calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation6538,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/attachments",userid: string,calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation6539,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/attachments/{attachment-id}",userid: string,calendarGroupid: string,calendarid: string,eventid: string,eventid1: string,attachmentid: string):operation6540,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/attachments/$count",userid: string,calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation6541,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/attachments/microsoft.graph.createUploadSession",userid: string,calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation6542,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/calendar",userid: string,calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation6543,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/extensions",userid: string,calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation6544,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/extensions/{extension-id}",userid: string,calendarGroupid: string,calendarid: string,eventid: string,eventid1: string,extensionid: string):operation6545,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/extensions/$count",userid: string,calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation6546,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.accept",userid: string,calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation6547,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.cancel",userid: string,calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation6548,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.decline",userid: string,calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation6549,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.dismissReminder",userid: string,calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation6550,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.forward",userid: string,calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation6551,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.snoozeReminder",userid: string,calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation6552,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.tentativelyAccept",userid: string,calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation6553,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties",userid: string,calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation6554,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}",userid: string,calendarGroupid: string,calendarid: string,eventid: string,eventid1: string,multiValueLegacyExtendedPropertyid: string):operation6555,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties/$count",userid: string,calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation6556,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties",userid: string,calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation6557,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}",userid: string,calendarGroupid: string,calendarid: string,eventid: string,eventid1: string,singleValueLegacyExtendedPropertyid: string):operation6558,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties/$count",userid: string,calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation6559,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/$count",userid: string,calendarGroupid: string,calendarid: string,eventid: string):operation6560,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/microsoft.graph.delta()",userid: string,calendarGroupid: string,calendarid: string,eventid: string):operation6561,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/microsoft.graph.accept",userid: string,calendarGroupid: string,calendarid: string,eventid: string):operation6562,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/microsoft.graph.cancel",userid: string,calendarGroupid: string,calendarid: string,eventid: string):operation6563,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/microsoft.graph.decline",userid: string,calendarGroupid: string,calendarid: string,eventid: string):operation6564,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/microsoft.graph.dismissReminder",userid: string,calendarGroupid: string,calendarid: string,eventid: string):operation6565,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/microsoft.graph.forward",userid: string,calendarGroupid: string,calendarid: string,eventid: string):operation6566,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/microsoft.graph.snoozeReminder",userid: string,calendarGroupid: string,calendarid: string,eventid: string):operation6567,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/microsoft.graph.tentativelyAccept",userid: string,calendarGroupid: string,calendarid: string,eventid: string):operation6568,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/multiValueExtendedProperties",userid: string,calendarGroupid: string,calendarid: string,eventid: string):operation6569,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}",userid: string,calendarGroupid: string,calendarid: string,eventid: string,multiValueLegacyExtendedPropertyid: string):operation6570,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/multiValueExtendedProperties/$count",userid: string,calendarGroupid: string,calendarid: string,eventid: string):operation6571,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/singleValueExtendedProperties",userid: string,calendarGroupid: string,calendarid: string,eventid: string):operation6572,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}",userid: string,calendarGroupid: string,calendarid: string,eventid: string,singleValueLegacyExtendedPropertyid: string):operation6573,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/singleValueExtendedProperties/$count",userid: string,calendarGroupid: string,calendarid: string,eventid: string):operation6574,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/$count",userid: string,calendarGroupid: string,calendarid: string):operation6575,
    (api:"/users/{user-id}/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/microsoft.graph.delta()",userid: string,calendarGroupid: string,calendarid: string):operation6576,
    (api:"/users/{user-id}/calendars/{calendar-id}/events",userid: string,calendarid: string):operation6642,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}",userid: string,calendarid: string,eventid: string):operation6643,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/attachments",userid: string,calendarid: string,eventid: string):operation6644,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/attachments/{attachment-id}",userid: string,calendarid: string,eventid: string,attachmentid: string):operation6645,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/attachments/$count",userid: string,calendarid: string,eventid: string):operation6646,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/attachments/microsoft.graph.createUploadSession",userid: string,calendarid: string,eventid: string):operation6647,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/calendar",userid: string,calendarid: string,eventid: string):operation6648,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/extensions",userid: string,calendarid: string,eventid: string):operation6649,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/extensions/{extension-id}",userid: string,calendarid: string,eventid: string,extensionid: string):operation6650,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/extensions/$count",userid: string,calendarid: string,eventid: string):operation6651,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/instances",userid: string,calendarid: string,eventid: string):operation6652,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}",userid: string,calendarid: string,eventid: string,eventid1: string):operation6653,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/attachments",userid: string,calendarid: string,eventid: string,eventid1: string):operation6654,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/attachments/{attachment-id}",userid: string,calendarid: string,eventid: string,eventid1: string,attachmentid: string):operation6655,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/attachments/$count",userid: string,calendarid: string,eventid: string,eventid1: string):operation6656,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/attachments/microsoft.graph.createUploadSession",userid: string,calendarid: string,eventid: string,eventid1: string):operation6657,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/calendar",userid: string,calendarid: string,eventid: string,eventid1: string):operation6658,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/extensions",userid: string,calendarid: string,eventid: string,eventid1: string):operation6659,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/extensions/{extension-id}",userid: string,calendarid: string,eventid: string,eventid1: string,extensionid: string):operation6660,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/extensions/$count",userid: string,calendarid: string,eventid: string,eventid1: string):operation6661,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.accept",userid: string,calendarid: string,eventid: string,eventid1: string):operation6662,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.cancel",userid: string,calendarid: string,eventid: string,eventid1: string):operation6663,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.decline",userid: string,calendarid: string,eventid: string,eventid1: string):operation6664,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.dismissReminder",userid: string,calendarid: string,eventid: string,eventid1: string):operation6665,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.forward",userid: string,calendarid: string,eventid: string,eventid1: string):operation6666,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.snoozeReminder",userid: string,calendarid: string,eventid: string,eventid1: string):operation6667,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.tentativelyAccept",userid: string,calendarid: string,eventid: string,eventid1: string):operation6668,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties",userid: string,calendarid: string,eventid: string,eventid1: string):operation6669,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}",userid: string,calendarid: string,eventid: string,eventid1: string,multiValueLegacyExtendedPropertyid: string):operation6670,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties/$count",userid: string,calendarid: string,eventid: string,eventid1: string):operation6671,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties",userid: string,calendarid: string,eventid: string,eventid1: string):operation6672,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}",userid: string,calendarid: string,eventid: string,eventid1: string,singleValueLegacyExtendedPropertyid: string):operation6673,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties/$count",userid: string,calendarid: string,eventid: string,eventid1: string):operation6674,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/instances/$count",userid: string,calendarid: string,eventid: string):operation6675,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/instances/microsoft.graph.delta()",userid: string,calendarid: string,eventid: string):operation6676,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/microsoft.graph.accept",userid: string,calendarid: string,eventid: string):operation6677,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/microsoft.graph.cancel",userid: string,calendarid: string,eventid: string):operation6678,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/microsoft.graph.decline",userid: string,calendarid: string,eventid: string):operation6679,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/microsoft.graph.dismissReminder",userid: string,calendarid: string,eventid: string):operation6680,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/microsoft.graph.forward",userid: string,calendarid: string,eventid: string):operation6681,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/microsoft.graph.snoozeReminder",userid: string,calendarid: string,eventid: string):operation6682,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/microsoft.graph.tentativelyAccept",userid: string,calendarid: string,eventid: string):operation6683,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/multiValueExtendedProperties",userid: string,calendarid: string,eventid: string):operation6684,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}",userid: string,calendarid: string,eventid: string,multiValueLegacyExtendedPropertyid: string):operation6685,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/multiValueExtendedProperties/$count",userid: string,calendarid: string,eventid: string):operation6686,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/singleValueExtendedProperties",userid: string,calendarid: string,eventid: string):operation6687,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}",userid: string,calendarid: string,eventid: string,singleValueLegacyExtendedPropertyid: string):operation6688,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/{event-id}/singleValueExtendedProperties/$count",userid: string,calendarid: string,eventid: string):operation6689,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/$count",userid: string,calendarid: string):operation6690,
    (api:"/users/{user-id}/calendars/{calendar-id}/events/microsoft.graph.delta()",userid: string,calendarid: string):operation6691,

    (api:"/users/{user-id}/events",userid: string):operation7058,
    (api:"/users/{user-id}/events/{event-id}",userid: string,eventid: string):operation7059,
    (api:"/users/{user-id}/events/{event-id}/attachments",userid: string,eventid: string):operation7060,
    (api:"/users/{user-id}/events/{event-id}/attachments/{attachment-id}",userid: string,eventid: string,attachmentid: string):operation7061,
    (api:"/users/{user-id}/events/{event-id}/attachments/$count",userid: string,eventid: string):operation7062,
    (api:"/users/{user-id}/events/{event-id}/attachments/microsoft.graph.createUploadSession",userid: string,eventid: string):operation7063,
    (api:"/users/{user-id}/events/{event-id}/calendar",userid: string,eventid: string):operation7064,
    (api:"/users/{user-id}/events/{event-id}/extensions",userid: string,eventid: string):operation7065,
    (api:"/users/{user-id}/events/{event-id}/extensions/{extension-id}",userid: string,eventid: string,extensionid: string):operation7066,
    (api:"/users/{user-id}/events/{event-id}/extensions/$count",userid: string,eventid: string):operation7067,
    (api:"/users/{user-id}/events/{event-id}/instances",userid: string,eventid: string):operation7068,
    (api:"/users/{user-id}/events/{event-id}/instances/{event-id1}",userid: string,eventid: string,eventid1: string):operation7069,
    (api:"/users/{user-id}/events/{event-id}/instances/{event-id1}/attachments",userid: string,eventid: string,eventid1: string):operation7070,
    (api:"/users/{user-id}/events/{event-id}/instances/{event-id1}/attachments/{attachment-id}",userid: string,eventid: string,eventid1: string,attachmentid: string):operation7071,
    (api:"/users/{user-id}/events/{event-id}/instances/{event-id1}/attachments/$count",userid: string,eventid: string,eventid1: string):operation7072,
    (api:"/users/{user-id}/events/{event-id}/instances/{event-id1}/attachments/microsoft.graph.createUploadSession",userid: string,eventid: string,eventid1: string):operation7073,
    (api:"/users/{user-id}/events/{event-id}/instances/{event-id1}/calendar",userid: string,eventid: string,eventid1: string):operation7074,
    (api:"/users/{user-id}/events/{event-id}/instances/{event-id1}/extensions",userid: string,eventid: string,eventid1: string):operation7075,
    (api:"/users/{user-id}/events/{event-id}/instances/{event-id1}/extensions/{extension-id}",userid: string,eventid: string,eventid1: string,extensionid: string):operation7076,
    (api:"/users/{user-id}/events/{event-id}/instances/{event-id1}/extensions/$count",userid: string,eventid: string,eventid1: string):operation7077,
    (api:"/users/{user-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.accept",userid: string,eventid: string,eventid1: string):operation7078,
    (api:"/users/{user-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.cancel",userid: string,eventid: string,eventid1: string):operation7079,
    (api:"/users/{user-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.decline",userid: string,eventid: string,eventid1: string):operation7080,
    (api:"/users/{user-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.dismissReminder",userid: string,eventid: string,eventid1: string):operation7081,
    (api:"/users/{user-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.forward",userid: string,eventid: string,eventid1: string):operation7082,
    (api:"/users/{user-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.snoozeReminder",userid: string,eventid: string,eventid1: string):operation7083,
    (api:"/users/{user-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.tentativelyAccept",userid: string,eventid: string,eventid1: string):operation7084,
    (api:"/users/{user-id}/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties",userid: string,eventid: string,eventid1: string):operation7085,
    (api:"/users/{user-id}/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}",userid: string,eventid: string,eventid1: string,multiValueLegacyExtendedPropertyid: string):operation7086,
    (api:"/users/{user-id}/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties/$count",userid: string,eventid: string,eventid1: string):operation7087,
    (api:"/users/{user-id}/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties",userid: string,eventid: string,eventid1: string):operation7088,
    (api:"/users/{user-id}/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}",userid: string,eventid: string,eventid1: string,singleValueLegacyExtendedPropertyid: string):operation7089,
    (api:"/users/{user-id}/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties/$count",userid: string,eventid: string,eventid1: string):operation7090,
    (api:"/users/{user-id}/events/{event-id}/instances/$count",userid: string,eventid: string):operation7091,
    (api:"/users/{user-id}/events/{event-id}/instances/microsoft.graph.delta()",userid: string,eventid: string):operation7092,
    (api:"/users/{user-id}/events/{event-id}/microsoft.graph.accept",userid: string,eventid: string):operation7093,
    (api:"/users/{user-id}/events/{event-id}/microsoft.graph.cancel",userid: string,eventid: string):operation7094,
    (api:"/users/{user-id}/events/{event-id}/microsoft.graph.decline",userid: string,eventid: string):operation7095,
    (api:"/users/{user-id}/events/{event-id}/microsoft.graph.dismissReminder",userid: string,eventid: string):operation7096,
    (api:"/users/{user-id}/events/{event-id}/microsoft.graph.forward",userid: string,eventid: string):operation7097,
    (api:"/users/{user-id}/events/{event-id}/microsoft.graph.snoozeReminder",userid: string,eventid: string):operation7098,
    (api:"/users/{user-id}/events/{event-id}/microsoft.graph.tentativelyAccept",userid: string,eventid: string):operation7099,
    (api:"/users/{user-id}/events/{event-id}/multiValueExtendedProperties",userid: string,eventid: string):operation7100,
    (api:"/users/{user-id}/events/{event-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}",userid: string,eventid: string,multiValueLegacyExtendedPropertyid: string):operation7101,
    (api:"/users/{user-id}/events/{event-id}/multiValueExtendedProperties/$count",userid: string,eventid: string):operation7102,
    (api:"/users/{user-id}/events/{event-id}/singleValueExtendedProperties",userid: string,eventid: string):operation7103,
    (api:"/users/{user-id}/events/{event-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}",userid: string,eventid: string,singleValueLegacyExtendedPropertyid: string):operation7104,
    (api:"/users/{user-id}/events/{event-id}/singleValueExtendedProperties/$count",userid: string,eventid: string):operation7105,
    (api:"/users/{user-id}/events/$count",userid: string):operation7106,
    (api:"/users/{user-id}/events/microsoft.graph.delta()",userid: string):operation7107,

    (api:"/groups/{group-id}/calendar/events",groupid: string):operation1498,
    (api:"/groups/{group-id}/calendar/events/{event-id}",groupid: string,eventid: string):operation1499,
    (api:"/groups/{group-id}/calendar/events/{event-id}/attachments",groupid: string,eventid: string):operation1500,
    (api:"/groups/{group-id}/calendar/events/{event-id}/attachments/{attachment-id}",groupid: string,eventid: string,attachmentid: string):operation1501,
    (api:"/groups/{group-id}/calendar/events/{event-id}/attachments/$count",groupid: string,eventid: string):operation1502,
    (api:"/groups/{group-id}/calendar/events/{event-id}/attachments/microsoft.graph.createUploadSession",groupid: string,eventid: string):operation1503,
    (api:"/groups/{group-id}/calendar/events/{event-id}/calendar",groupid: string,eventid: string):operation1504,
    (api:"/groups/{group-id}/calendar/events/{event-id}/extensions",groupid: string,eventid: string):operation1505,
    (api:"/groups/{group-id}/calendar/events/{event-id}/extensions/{extension-id}",groupid: string,eventid: string,extensionid: string):operation1506,
    (api:"/groups/{group-id}/calendar/events/{event-id}/extensions/$count",groupid: string,eventid: string):operation1507,
    (api:"/groups/{group-id}/calendar/events/{event-id}/instances",groupid: string,eventid: string):operation1508,
    (api:"/groups/{group-id}/calendar/events/{event-id}/instances/{event-id1}",groupid: string,eventid: string,eventid1: string):operation1509,
    (api:"/groups/{group-id}/calendar/events/{event-id}/instances/{event-id1}/attachments",groupid: string,eventid: string,eventid1: string):operation1510,
    (api:"/groups/{group-id}/calendar/events/{event-id}/instances/{event-id1}/attachments/{attachment-id}",groupid: string,eventid: string,eventid1: string,attachmentid: string):operation1511,
    (api:"/groups/{group-id}/calendar/events/{event-id}/instances/{event-id1}/attachments/$count",groupid: string,eventid: string,eventid1: string):operation1512,
    (api:"/groups/{group-id}/calendar/events/{event-id}/instances/{event-id1}/attachments/microsoft.graph.createUploadSession",groupid: string,eventid: string,eventid1: string):operation1513,
    (api:"/groups/{group-id}/calendar/events/{event-id}/instances/{event-id1}/calendar",groupid: string,eventid: string,eventid1: string):operation1514,
    (api:"/groups/{group-id}/calendar/events/{event-id}/instances/{event-id1}/extensions",groupid: string,eventid: string,eventid1: string):operation1515,
    (api:"/groups/{group-id}/calendar/events/{event-id}/instances/{event-id1}/extensions/{extension-id}",groupid: string,eventid: string,eventid1: string,extensionid: string):operation1516,
    (api:"/groups/{group-id}/calendar/events/{event-id}/instances/{event-id1}/extensions/$count",groupid: string,eventid: string,eventid1: string):operation1517,
    (api:"/groups/{group-id}/calendar/events/{event-id}/instances/{event-id1}/microsoft.graph.accept",groupid: string,eventid: string,eventid1: string):operation1518,
    (api:"/groups/{group-id}/calendar/events/{event-id}/instances/{event-id1}/microsoft.graph.cancel",groupid: string,eventid: string,eventid1: string):operation1519,
    (api:"/groups/{group-id}/calendar/events/{event-id}/instances/{event-id1}/microsoft.graph.decline",groupid: string,eventid: string,eventid1: string):operation1520,
    (api:"/groups/{group-id}/calendar/events/{event-id}/instances/{event-id1}/microsoft.graph.dismissReminder",groupid: string,eventid: string,eventid1: string):operation1521,
    (api:"/groups/{group-id}/calendar/events/{event-id}/instances/{event-id1}/microsoft.graph.forward",groupid: string,eventid: string,eventid1: string):operation1522,
    (api:"/groups/{group-id}/calendar/events/{event-id}/instances/{event-id1}/microsoft.graph.snoozeReminder",groupid: string,eventid: string,eventid1: string):operation1523,
    (api:"/groups/{group-id}/calendar/events/{event-id}/instances/{event-id1}/microsoft.graph.tentativelyAccept",groupid: string,eventid: string,eventid1: string):operation1524,
    (api:"/groups/{group-id}/calendar/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties",groupid: string,eventid: string,eventid1: string):operation1525,
    (api:"/groups/{group-id}/calendar/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}",groupid: string,eventid: string,eventid1: string,multiValueLegacyExtendedPropertyid: string):operation1526,
    (api:"/groups/{group-id}/calendar/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties/$count",groupid: string,eventid: string,eventid1: string):operation1527,
    (api:"/groups/{group-id}/calendar/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties",groupid: string,eventid: string,eventid1: string):operation1528,
    (api:"/groups/{group-id}/calendar/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}",groupid: string,eventid: string,eventid1: string,singleValueLegacyExtendedPropertyid: string):operation1529,
    (api:"/groups/{group-id}/calendar/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties/$count",groupid: string,eventid: string,eventid1: string):operation1530,
    (api:"/groups/{group-id}/calendar/events/{event-id}/instances/$count",groupid: string,eventid: string):operation1531,
    (api:"/groups/{group-id}/calendar/events/{event-id}/instances/microsoft.graph.delta()",groupid: string,eventid: string):operation1532,
    (api:"/groups/{group-id}/calendar/events/{event-id}/microsoft.graph.accept",groupid: string,eventid: string):operation1533,
    (api:"/groups/{group-id}/calendar/events/{event-id}/microsoft.graph.cancel",groupid: string,eventid: string):operation1534,
    (api:"/groups/{group-id}/calendar/events/{event-id}/microsoft.graph.decline",groupid: string,eventid: string):operation1535,
    (api:"/groups/{group-id}/calendar/events/{event-id}/microsoft.graph.dismissReminder",groupid: string,eventid: string):operation1536,
    (api:"/groups/{group-id}/calendar/events/{event-id}/microsoft.graph.forward",groupid: string,eventid: string):operation1537,
    (api:"/groups/{group-id}/calendar/events/{event-id}/microsoft.graph.snoozeReminder",groupid: string,eventid: string):operation1538,
    (api:"/groups/{group-id}/calendar/events/{event-id}/microsoft.graph.tentativelyAccept",groupid: string,eventid: string):operation1539,
    (api:"/groups/{group-id}/calendar/events/{event-id}/multiValueExtendedProperties",groupid: string,eventid: string):operation1540,
    (api:"/groups/{group-id}/calendar/events/{event-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}",groupid: string,eventid: string,multiValueLegacyExtendedPropertyid: string):operation1541,
    (api:"/groups/{group-id}/calendar/events/{event-id}/multiValueExtendedProperties/$count",groupid: string,eventid: string):operation1542,
    (api:"/groups/{group-id}/calendar/events/{event-id}/singleValueExtendedProperties",groupid: string,eventid: string):operation1543,
    (api:"/groups/{group-id}/calendar/events/{event-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}",groupid: string,eventid: string,singleValueLegacyExtendedPropertyid: string):operation1544,
    (api:"/groups/{group-id}/calendar/events/{event-id}/singleValueExtendedProperties/$count",groupid: string,eventid: string):operation1545,
    (api:"/groups/{group-id}/calendar/events/$count",groupid: string):operation1546,
    (api:"/groups/{group-id}/calendar/events/microsoft.graph.delta()",groupid: string):operation1547,

    (api:"/groups/{group-id}/events",groupid: string):operation1835,
    (api:"/groups/{group-id}/events/{event-id}",groupid: string,eventid: string):operation1836,
    (api:"/groups/{group-id}/events/{event-id}/attachments",groupid: string,eventid: string):operation1837,
    (api:"/groups/{group-id}/events/{event-id}/attachments/{attachment-id}",groupid: string,eventid: string,attachmentid: string):operation1838,
    (api:"/groups/{group-id}/events/{event-id}/attachments/$count",groupid: string,eventid: string):operation1839,
    (api:"/groups/{group-id}/events/{event-id}/attachments/microsoft.graph.createUploadSession",groupid: string,eventid: string):operation1840,
    (api:"/groups/{group-id}/events/{event-id}/calendar",groupid: string,eventid: string):operation1841,
    (api:"/groups/{group-id}/events/{event-id}/extensions",groupid: string,eventid: string):operation1842,
    (api:"/groups/{group-id}/events/{event-id}/extensions/{extension-id}",groupid: string,eventid: string,extensionid: string):operation1843,
    (api:"/groups/{group-id}/events/{event-id}/extensions/$count",groupid: string,eventid: string):operation1844,
    (api:"/groups/{group-id}/events/{event-id}/instances",groupid: string,eventid: string):operation1845,
    (api:"/groups/{group-id}/events/{event-id}/instances/{event-id1}",groupid: string,eventid: string,eventid1: string):operation1846,
    (api:"/groups/{group-id}/events/{event-id}/instances/{event-id1}/attachments",groupid: string,eventid: string,eventid1: string):operation1847,
    (api:"/groups/{group-id}/events/{event-id}/instances/{event-id1}/attachments/{attachment-id}",groupid: string,eventid: string,eventid1: string,attachmentid: string):operation1848,
    (api:"/groups/{group-id}/events/{event-id}/instances/{event-id1}/attachments/$count",groupid: string,eventid: string,eventid1: string):operation1849,
    (api:"/groups/{group-id}/events/{event-id}/instances/{event-id1}/attachments/microsoft.graph.createUploadSession",groupid: string,eventid: string,eventid1: string):operation1850,
    (api:"/groups/{group-id}/events/{event-id}/instances/{event-id1}/calendar",groupid: string,eventid: string,eventid1: string):operation1851,
    (api:"/groups/{group-id}/events/{event-id}/instances/{event-id1}/extensions",groupid: string,eventid: string,eventid1: string):operation1852,
    (api:"/groups/{group-id}/events/{event-id}/instances/{event-id1}/extensions/{extension-id}",groupid: string,eventid: string,eventid1: string,extensionid: string):operation1853,
    (api:"/groups/{group-id}/events/{event-id}/instances/{event-id1}/extensions/$count",groupid: string,eventid: string,eventid1: string):operation1854,
    (api:"/groups/{group-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.accept",groupid: string,eventid: string,eventid1: string):operation1855,
    (api:"/groups/{group-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.cancel",groupid: string,eventid: string,eventid1: string):operation1856,
    (api:"/groups/{group-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.decline",groupid: string,eventid: string,eventid1: string):operation1857,
    (api:"/groups/{group-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.dismissReminder",groupid: string,eventid: string,eventid1: string):operation1858,
    (api:"/groups/{group-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.forward",groupid: string,eventid: string,eventid1: string):operation1859,
    (api:"/groups/{group-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.snoozeReminder",groupid: string,eventid: string,eventid1: string):operation1860,
    (api:"/groups/{group-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.tentativelyAccept",groupid: string,eventid: string,eventid1: string):operation1861,
    (api:"/groups/{group-id}/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties",groupid: string,eventid: string,eventid1: string):operation1862,
    (api:"/groups/{group-id}/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}",groupid: string,eventid: string,eventid1: string,multiValueLegacyExtendedPropertyid: string):operation1863,
    (api:"/groups/{group-id}/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties/$count",groupid: string,eventid: string,eventid1: string):operation1864,
    (api:"/groups/{group-id}/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties",groupid: string,eventid: string,eventid1: string):operation1865,
    (api:"/groups/{group-id}/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}",groupid: string,eventid: string,eventid1: string,singleValueLegacyExtendedPropertyid: string):operation1866,
    (api:"/groups/{group-id}/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties/$count",groupid: string,eventid: string,eventid1: string):operation1867,
    (api:"/groups/{group-id}/events/{event-id}/instances/$count",groupid: string,eventid: string):operation1868,
    (api:"/groups/{group-id}/events/{event-id}/instances/microsoft.graph.delta()",groupid: string,eventid: string):operation1869,
    (api:"/groups/{group-id}/events/{event-id}/microsoft.graph.accept",groupid: string,eventid: string):operation1870,
    (api:"/groups/{group-id}/events/{event-id}/microsoft.graph.cancel",groupid: string,eventid: string):operation1871,
    (api:"/groups/{group-id}/events/{event-id}/microsoft.graph.decline",groupid: string,eventid: string):operation1872,
    (api:"/groups/{group-id}/events/{event-id}/microsoft.graph.dismissReminder",groupid: string,eventid: string):operation1873,
    (api:"/groups/{group-id}/events/{event-id}/microsoft.graph.forward",groupid: string,eventid: string):operation1874,
    (api:"/groups/{group-id}/events/{event-id}/microsoft.graph.snoozeReminder",groupid: string,eventid: string):operation1875,
    (api:"/groups/{group-id}/events/{event-id}/microsoft.graph.tentativelyAccept",groupid: string,eventid: string):operation1876,
    (api:"/groups/{group-id}/events/{event-id}/multiValueExtendedProperties",groupid: string,eventid: string):operation1877,
    (api:"/groups/{group-id}/events/{event-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}",groupid: string,eventid: string,multiValueLegacyExtendedPropertyid: string):operation1878,
    (api:"/groups/{group-id}/events/{event-id}/multiValueExtendedProperties/$count",groupid: string,eventid: string):operation1879,
    (api:"/groups/{group-id}/events/{event-id}/singleValueExtendedProperties",groupid: string,eventid: string):operation1880,
    (api:"/groups/{group-id}/events/{event-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}",groupid: string,eventid: string,singleValueLegacyExtendedPropertyid: string):operation1881,
    (api:"/groups/{group-id}/events/{event-id}/singleValueExtendedProperties/$count",groupid: string,eventid: string):operation1882,
    (api:"/groups/{group-id}/events/$count",groupid: string):operation1883,
    (api:"/groups/{group-id}/events/microsoft.graph.delta()",groupid: string):operation1884,

    (api:"/me/calendar/events"):operation3399,
    (api:"/me/calendar/events/{event-id}",eventid: string):operation3400,
    (api:"/me/calendar/events/{event-id}/attachments",eventid: string):operation3401,
    (api:"/me/calendar/events/{event-id}/attachments/{attachment-id}",eventid: string,attachmentid: string):operation3402,
    (api:"/me/calendar/events/{event-id}/attachments/$count",eventid: string):operation3403,
    (api:"/me/calendar/events/{event-id}/attachments/microsoft.graph.createUploadSession",eventid: string):operation3404,
    (api:"/me/calendar/events/{event-id}/calendar",eventid: string):operation3405,
    (api:"/me/calendar/events/{event-id}/extensions",eventid: string):operation3406,
    (api:"/me/calendar/events/{event-id}/extensions/{extension-id}",eventid: string,extensionid: string):operation3407,
    (api:"/me/calendar/events/{event-id}/extensions/$count",eventid: string):operation3408,
    (api:"/me/calendar/events/{event-id}/instances",eventid: string):operation3409,
    (api:"/me/calendar/events/{event-id}/instances/{event-id1}",eventid: string,eventid1: string):operation3410,
    (api:"/me/calendar/events/{event-id}/instances/{event-id1}/attachments",eventid: string,eventid1: string):operation3411,
    (api:"/me/calendar/events/{event-id}/instances/{event-id1}/attachments/{attachment-id}",eventid: string,eventid1: string,attachmentid: string):operation3412,
    (api:"/me/calendar/events/{event-id}/instances/{event-id1}/attachments/$count",eventid: string,eventid1: string):operation3413,
    (api:"/me/calendar/events/{event-id}/instances/{event-id1}/attachments/microsoft.graph.createUploadSession",eventid: string,eventid1: string):operation3414,
    (api:"/me/calendar/events/{event-id}/instances/{event-id1}/calendar",eventid: string,eventid1: string):operation3415,
    (api:"/me/calendar/events/{event-id}/instances/{event-id1}/extensions",eventid: string,eventid1: string):operation3416,
    (api:"/me/calendar/events/{event-id}/instances/{event-id1}/extensions/{extension-id}",eventid: string,eventid1: string,extensionid: string):operation3417,
    (api:"/me/calendar/events/{event-id}/instances/{event-id1}/extensions/$count",eventid: string,eventid1: string):operation3418,
    (api:"/me/calendar/events/{event-id}/instances/{event-id1}/microsoft.graph.accept",eventid: string,eventid1: string):operation3419,
    (api:"/me/calendar/events/{event-id}/instances/{event-id1}/microsoft.graph.cancel",eventid: string,eventid1: string):operation3420,
    (api:"/me/calendar/events/{event-id}/instances/{event-id1}/microsoft.graph.decline",eventid: string,eventid1: string):operation3421,
    (api:"/me/calendar/events/{event-id}/instances/{event-id1}/microsoft.graph.dismissReminder",eventid: string,eventid1: string):operation3422,
    (api:"/me/calendar/events/{event-id}/instances/{event-id1}/microsoft.graph.forward",eventid: string,eventid1: string):operation3423,
    (api:"/me/calendar/events/{event-id}/instances/{event-id1}/microsoft.graph.snoozeReminder",eventid: string,eventid1: string):operation3424,
    (api:"/me/calendar/events/{event-id}/instances/{event-id1}/microsoft.graph.tentativelyAccept",eventid: string,eventid1: string):operation3425,
    (api:"/me/calendar/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties",eventid: string,eventid1: string):operation3426,
    (api:"/me/calendar/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}",eventid: string,eventid1: string,multiValueLegacyExtendedPropertyid: string):operation3427,
    (api:"/me/calendar/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties/$count",eventid: string,eventid1: string):operation3428,
    (api:"/me/calendar/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties",eventid: string,eventid1: string):operation3429,
    (api:"/me/calendar/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}",eventid: string,eventid1: string,singleValueLegacyExtendedPropertyid: string):operation3430,
    (api:"/me/calendar/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties/$count",eventid: string,eventid1: string):operation3431,
    (api:"/me/calendar/events/{event-id}/instances/$count",eventid: string):operation3432,
    (api:"/me/calendar/events/{event-id}/instances/microsoft.graph.delta()",eventid: string):operation3433,
    (api:"/me/calendar/events/{event-id}/microsoft.graph.accept",eventid: string):operation3434,
    (api:"/me/calendar/events/{event-id}/microsoft.graph.cancel",eventid: string):operation3435,
    (api:"/me/calendar/events/{event-id}/microsoft.graph.decline",eventid: string):operation3436,
    (api:"/me/calendar/events/{event-id}/microsoft.graph.dismissReminder",eventid: string):operation3437,
    (api:"/me/calendar/events/{event-id}/microsoft.graph.forward",eventid: string):operation3438,
    (api:"/me/calendar/events/{event-id}/microsoft.graph.snoozeReminder",eventid: string):operation3439,
    (api:"/me/calendar/events/{event-id}/microsoft.graph.tentativelyAccept",eventid: string):operation3440,
    (api:"/me/calendar/events/{event-id}/multiValueExtendedProperties",eventid: string):operation3441,
    (api:"/me/calendar/events/{event-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}",eventid: string,multiValueLegacyExtendedPropertyid: string):operation3442,
    (api:"/me/calendar/events/{event-id}/multiValueExtendedProperties/$count",eventid: string):operation3443,
    (api:"/me/calendar/events/{event-id}/singleValueExtendedProperties",eventid: string):operation3444,
    (api:"/me/calendar/events/{event-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}",eventid: string,singleValueLegacyExtendedPropertyid: string):operation3445,
    (api:"/me/calendar/events/{event-id}/singleValueExtendedProperties/$count",eventid: string):operation3446,
    (api:"/me/calendar/events/$count"):operation3447,
    (api:"/me/calendar/events/microsoft.graph.delta()"):operation3448,

    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events",calendarGroupid: string,calendarid: string):operation3514,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}",calendarGroupid: string,calendarid: string,eventid: string):operation3515,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/attachments",calendarGroupid: string,calendarid: string,eventid: string):operation3516,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/attachments/{attachment-id}",calendarGroupid: string,calendarid: string,eventid: string,attachmentid: string):operation3517,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/attachments/$count",calendarGroupid: string,calendarid: string,eventid: string):operation3518,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/attachments/microsoft.graph.createUploadSession",calendarGroupid: string,calendarid: string,eventid: string):operation3519,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/calendar",calendarGroupid: string,calendarid: string,eventid: string):operation3520,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/extensions",calendarGroupid: string,calendarid: string,eventid: string):operation3521,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/extensions/{extension-id}",calendarGroupid: string,calendarid: string,eventid: string,extensionid: string):operation3522,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/extensions/$count",calendarGroupid: string,calendarid: string,eventid: string):operation3523,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances",calendarGroupid: string,calendarid: string,eventid: string):operation3524,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}",calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation3525,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/attachments",calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation3526,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/attachments/{attachment-id}",calendarGroupid: string,calendarid: string,eventid: string,eventid1: string,attachmentid: string):operation3527,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/attachments/$count",calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation3528,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/attachments/microsoft.graph.createUploadSession",calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation3529,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/calendar",calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation3530,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/extensions",calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation3531,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/extensions/{extension-id}",calendarGroupid: string,calendarid: string,eventid: string,eventid1: string,extensionid: string):operation3532,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/extensions/$count",calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation3533,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.accept",calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation3534,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.cancel",calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation3535,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.decline",calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation3536,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.dismissReminder",calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation3537,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.forward",calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation3538,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.snoozeReminder",calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation3539,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.tentativelyAccept",calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation3540,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties",calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation3541,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}",calendarGroupid: string,calendarid: string,eventid: string,eventid1: string,multiValueLegacyExtendedPropertyid: string):operation3542,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties/$count",calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation3543,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties",calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation3544,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}",calendarGroupid: string,calendarid: string,eventid: string,eventid1: string,singleValueLegacyExtendedPropertyid: string):operation3545,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties/$count",calendarGroupid: string,calendarid: string,eventid: string,eventid1: string):operation3546,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/$count",calendarGroupid: string,calendarid: string,eventid: string):operation3547,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/instances/microsoft.graph.delta()",calendarGroupid: string,calendarid: string,eventid: string):operation3548,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/microsoft.graph.accept",calendarGroupid: string,calendarid: string,eventid: string):operation3549,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/microsoft.graph.cancel",calendarGroupid: string,calendarid: string,eventid: string):operation3550,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/microsoft.graph.decline",calendarGroupid: string,calendarid: string,eventid: string):operation3551,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/microsoft.graph.dismissReminder",calendarGroupid: string,calendarid: string,eventid: string):operation3552,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/microsoft.graph.forward",calendarGroupid: string,calendarid: string,eventid: string):operation3553,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/microsoft.graph.snoozeReminder",calendarGroupid: string,calendarid: string,eventid: string):operation3554,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/microsoft.graph.tentativelyAccept",calendarGroupid: string,calendarid: string,eventid: string):operation3555,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/multiValueExtendedProperties",calendarGroupid: string,calendarid: string,eventid: string):operation3556,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}",calendarGroupid: string,calendarid: string,eventid: string,multiValueLegacyExtendedPropertyid: string):operation3557,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/multiValueExtendedProperties/$count",calendarGroupid: string,calendarid: string,eventid: string):operation3558,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/singleValueExtendedProperties",calendarGroupid: string,calendarid: string,eventid: string):operation3559,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}",calendarGroupid: string,calendarid: string,eventid: string,singleValueLegacyExtendedPropertyid: string):operation3560,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/singleValueExtendedProperties/$count",calendarGroupid: string,calendarid: string,eventid: string):operation3561,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/$count",calendarGroupid: string,calendarid: string):operation3562,
    (api:"/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/microsoft.graph.delta()",calendarGroupid: string,calendarid: string):operation3563,
    (api:"/me/calendars/{calendar-id}/events",calendarid: string):operation3629,
    (api:"/me/calendars/{calendar-id}/events/{event-id}",calendarid: string,eventid: string):operation3630,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/attachments",calendarid: string,eventid: string):operation3631,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/attachments/{attachment-id}",calendarid: string,eventid: string,attachmentid: string):operation3632,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/attachments/$count",calendarid: string,eventid: string):operation3633,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/attachments/microsoft.graph.createUploadSession",calendarid: string,eventid: string):operation3634,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/calendar",calendarid: string,eventid: string):operation3635,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/extensions",calendarid: string,eventid: string):operation3636,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/extensions/{extension-id}",calendarid: string,eventid: string,extensionid: string):operation3637,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/extensions/$count",calendarid: string,eventid: string):operation3638,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/instances",calendarid: string,eventid: string):operation3639,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}",calendarid: string,eventid: string,eventid1: string):operation3640,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/attachments",calendarid: string,eventid: string,eventid1: string):operation3641,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/attachments/{attachment-id}",calendarid: string,eventid: string,eventid1: string,attachmentid: string):operation3642,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/attachments/$count",calendarid: string,eventid: string,eventid1: string):operation3643,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/attachments/microsoft.graph.createUploadSession",calendarid: string,eventid: string,eventid1: string):operation3644,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/calendar",calendarid: string,eventid: string,eventid1: string):operation3645,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/extensions",calendarid: string,eventid: string,eventid1: string):operation3646,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/extensions/{extension-id}",calendarid: string,eventid: string,eventid1: string,extensionid: string):operation3647,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/extensions/$count",calendarid: string,eventid: string,eventid1: string):operation3648,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.accept",calendarid: string,eventid: string,eventid1: string):operation3649,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.cancel",calendarid: string,eventid: string,eventid1: string):operation3650,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.decline",calendarid: string,eventid: string,eventid1: string):operation3651,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.dismissReminder",calendarid: string,eventid: string,eventid1: string):operation3652,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.forward",calendarid: string,eventid: string,eventid1: string):operation3653,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.snoozeReminder",calendarid: string,eventid: string,eventid1: string):operation3654,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/microsoft.graph.tentativelyAccept",calendarid: string,eventid: string,eventid1: string):operation3655,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties",calendarid: string,eventid: string,eventid1: string):operation3656,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}",calendarid: string,eventid: string,eventid1: string,multiValueLegacyExtendedPropertyid: string):operation3657,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties/$count",calendarid: string,eventid: string,eventid1: string):operation3658,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties",calendarid: string,eventid: string,eventid1: string):operation3659,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}",calendarid: string,eventid: string,eventid1: string,singleValueLegacyExtendedPropertyid: string):operation3660,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties/$count",calendarid: string,eventid: string,eventid1: string):operation3661,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/instances/$count",calendarid: string,eventid: string):operation3662,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/instances/microsoft.graph.delta()",calendarid: string,eventid: string):operation3663,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/microsoft.graph.accept",calendarid: string,eventid: string):operation3664,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/microsoft.graph.cancel",calendarid: string,eventid: string):operation3665,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/microsoft.graph.decline",calendarid: string,eventid: string):operation3666,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/microsoft.graph.dismissReminder",calendarid: string,eventid: string):operation3667,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/microsoft.graph.forward",calendarid: string,eventid: string):operation3668,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/microsoft.graph.snoozeReminder",calendarid: string,eventid: string):operation3669,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/microsoft.graph.tentativelyAccept",calendarid: string,eventid: string):operation3670,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/multiValueExtendedProperties",calendarid: string,eventid: string):operation3671,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}",calendarid: string,eventid: string,multiValueLegacyExtendedPropertyid: string):operation3672,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/multiValueExtendedProperties/$count",calendarid: string,eventid: string):operation3673,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/singleValueExtendedProperties",calendarid: string,eventid: string):operation3674,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}",calendarid: string,eventid: string,singleValueLegacyExtendedPropertyid: string):operation3675,
    (api:"/me/calendars/{calendar-id}/events/{event-id}/singleValueExtendedProperties/$count",calendarid: string,eventid: string):operation3676,
    (api:"/me/calendars/{calendar-id}/events/$count",calendarid: string):operation3677,
    (api:"/me/calendars/{calendar-id}/events/microsoft.graph.delta()",calendarid: string):operation3678,
    (api:"/me/events"):operation4045,
    (api:"/me/events/{event-id}",eventid: string):operation4046,
    (api:"/me/events/{event-id}/attachments",eventid: string):operation4047,
    (api:"/me/events/{event-id}/attachments/{attachment-id}",eventid: string,attachmentid: string):operation4048,
    (api:"/me/events/{event-id}/attachments/$count",eventid: string):operation4049,
    (api:"/me/events/{event-id}/attachments/microsoft.graph.createUploadSession",eventid: string):operation4050,
    (api:"/me/events/{event-id}/calendar",eventid: string):operation4051,
    (api:"/me/events/{event-id}/extensions",eventid: string):operation4052,
    (api:"/me/events/{event-id}/extensions/{extension-id}",eventid: string,extensionid: string):operation4053,
    (api:"/me/events/{event-id}/extensions/$count",eventid: string):operation4054,
    (api:"/me/events/{event-id}/instances",eventid: string):operation4055,
    (api:"/me/events/{event-id}/instances/{event-id1}",eventid: string,eventid1: string):operation4056,
    (api:"/me/events/{event-id}/instances/{event-id1}/attachments",eventid: string,eventid1: string):operation4057,
    (api:"/me/events/{event-id}/instances/{event-id1}/attachments/{attachment-id}",eventid: string,eventid1: string,attachmentid: string):operation4058,
    (api:"/me/events/{event-id}/instances/{event-id1}/attachments/$count",eventid: string,eventid1: string):operation4059,
    (api:"/me/events/{event-id}/instances/{event-id1}/attachments/microsoft.graph.createUploadSession",eventid: string,eventid1: string):operation4060,
    (api:"/me/events/{event-id}/instances/{event-id1}/calendar",eventid: string,eventid1: string):operation4061,
    (api:"/me/events/{event-id}/instances/{event-id1}/extensions",eventid: string,eventid1: string):operation4062,
    (api:"/me/events/{event-id}/instances/{event-id1}/extensions/{extension-id}",eventid: string,eventid1: string,extensionid: string):operation4063,
    (api:"/me/events/{event-id}/instances/{event-id1}/extensions/$count",eventid: string,eventid1: string):operation4064,
    (api:"/me/events/{event-id}/instances/{event-id1}/microsoft.graph.accept",eventid: string,eventid1: string):operation4065,
    (api:"/me/events/{event-id}/instances/{event-id1}/microsoft.graph.cancel",eventid: string,eventid1: string):operation4066,
    (api:"/me/events/{event-id}/instances/{event-id1}/microsoft.graph.decline",eventid: string,eventid1: string):operation4067,
    (api:"/me/events/{event-id}/instances/{event-id1}/microsoft.graph.dismissReminder",eventid: string,eventid1: string):operation4068,
    (api:"/me/events/{event-id}/instances/{event-id1}/microsoft.graph.forward",eventid: string,eventid1: string):operation4069,
    (api:"/me/events/{event-id}/instances/{event-id1}/microsoft.graph.snoozeReminder",eventid: string,eventid1: string):operation4070,
    (api:"/me/events/{event-id}/instances/{event-id1}/microsoft.graph.tentativelyAccept",eventid: string,eventid1: string):operation4071,
    (api:"/me/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties",eventid: string,eventid1: string):operation4072,
    (api:"/me/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}",eventid: string,eventid1: string,multiValueLegacyExtendedPropertyid: string):operation4073,
    (api:"/me/events/{event-id}/instances/{event-id1}/multiValueExtendedProperties/$count",eventid: string,eventid1: string):operation4074,
    (api:"/me/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties",eventid: string,eventid1: string):operation4075,
    (api:"/me/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}",eventid: string,eventid1: string,singleValueLegacyExtendedPropertyid: string):operation4076,
    (api:"/me/events/{event-id}/instances/{event-id1}/singleValueExtendedProperties/$count",eventid: string,eventid1: string):operation4077,
    (api:"/me/events/{event-id}/instances/$count",eventid: string):operation4078,
    (api:"/me/events/{event-id}/instances/microsoft.graph.delta()",eventid: string):operation4079,
    (api:"/me/events/{event-id}/microsoft.graph.accept",eventid: string):operation4080,
    (api:"/me/events/{event-id}/microsoft.graph.cancel",eventid: string):operation4081,
    (api:"/me/events/{event-id}/microsoft.graph.decline",eventid: string):operation4082,
    (api:"/me/events/{event-id}/microsoft.graph.dismissReminder",eventid: string):operation4083,
    (api:"/me/events/{event-id}/microsoft.graph.forward",eventid: string):operation4084,
    (api:"/me/events/{event-id}/microsoft.graph.snoozeReminder",eventid: string):operation4085,
    (api:"/me/events/{event-id}/microsoft.graph.tentativelyAccept",eventid: string):operation4086,
    (api:"/me/events/{event-id}/multiValueExtendedProperties",eventid: string):operation4087,
    (api:"/me/events/{event-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}",eventid: string,multiValueLegacyExtendedPropertyid: string):operation4088,
    (api:"/me/events/{event-id}/multiValueExtendedProperties/$count",eventid: string):operation4089,
    (api:"/me/events/{event-id}/singleValueExtendedProperties",eventid: string):operation4090,
    (api:"/me/events/{event-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}",eventid: string,singleValueLegacyExtendedPropertyid: string):operation4091,
    (api:"/me/events/{event-id}/singleValueExtendedProperties/$count",eventid: string):operation4092,
    (api:"/me/events/$count"):operation4093,
    (api:"/me/events/microsoft.graph.delta()"):operation4094,