(api:"/places"):operation4750,
(api:"/places/{place-id}",placeid: string):operation4751,
(api:"/places/{place-id}/microsoft.graph.room",placeid: string):operation4752,
(api:"/places/$count"):operation4753,
(api:"/places/microsoft.graph.room"):operation4754,
(api:"/places/microsoft.graph.room/$count"):operation4755,