(api:"/privacy"):operation4908,
    (api:"/privacy/subjectRightsRequests"):operation4909,
    (api:"/privacy/subjectRightsRequests/{subjectRightsRequest-id}",subjectRightsRequestid: string):operation4910,
    (api:"/privacy/subjectRightsRequests/{subjectRightsRequest-id}/microsoft.graph.getFinalAttachment()",subjectRightsRequestid: string):operation4911,
    (api:"/privacy/subjectRightsRequests/{subjectRightsRequest-id}/microsoft.graph.getFinalReport()",subjectRightsRequestid: string):operation4912,
    (api:"/privacy/subjectRightsRequests/{subjectRightsRequest-id}/notes",subjectRightsRequestid: string):operation4913,
    (api:"/privacy/subjectRightsRequests/{subjectRightsRequest-id}/notes/{authoredNote-id}",subjectRightsRequestid: string,authoredNoteid: string):operation4914,
    (api:"/privacy/subjectRightsRequests/{subjectRightsRequest-id}/notes/$count",subjectRightsRequestid: string):operation4915,
    (api:"/privacy/subjectRightsRequests/{subjectRightsRequest-id}/team",subjectRightsRequestid: string):operation4916,
    (api:"/privacy/subjectRightsRequests/$count"):operation4917,