(api:"/contacts"):operation258,
(api:"/contacts/{orgContact-id}",orgContactid: string):operation259,
(api:"/contacts/{orgContact-id}/directReports",orgContactid: string):operation260,
(api:"/contacts/{orgContact-id}/directReports/{directoryObject-id}",orgContactid: string,directoryObjectid: string):operation261,
(api:"/contacts/{orgContact-id}/directReports/{directoryObject-id}/microsoft.graph.orgContact",orgContactid: string,directoryObjectid: string):operation262,
(api:"/contacts/{orgContact-id}/directReports/{directoryObject-id}/microsoft.graph.user",orgContactid: string,directoryObjectid: string):operation263,
(api:"/contacts/{orgContact-id}/directReports/$count",orgContactid: string):operation264,
(api:"/contacts/{orgContact-id}/directReports/microsoft.graph.orgContact",orgContactid: string):operation265,
(api:"/contacts/{orgContact-id}/directReports/microsoft.graph.orgContact/$count",orgContactid: string):operation266,
(api:"/contacts/{orgContact-id}/directReports/microsoft.graph.user",orgContactid: string):operation267,
(api:"/contacts/{orgContact-id}/directReports/microsoft.graph.user/$count",orgContactid: string):operation268,
(api:"/contacts/{orgContact-id}/manager",orgContactid: string):operation269,
(api:"/contacts/{orgContact-id}/memberOf",orgContactid: string):operation270,
(api:"/contacts/{orgContact-id}/memberOf/{directoryObject-id}",orgContactid: string,directoryObjectid: string):operation271,
(api:"/contacts/{orgContact-id}/memberOf/{directoryObject-id}/microsoft.graph.application",orgContactid: string,directoryObjectid: string):operation272,
(api:"/contacts/{orgContact-id}/memberOf/{directoryObject-id}/microsoft.graph.device",orgContactid: string,directoryObjectid: string):operation273,
(api:"/contacts/{orgContact-id}/memberOf/{directoryObject-id}/microsoft.graph.group",orgContactid: string,directoryObjectid: string):operation274,
(api:"/contacts/{orgContact-id}/memberOf/{directoryObject-id}/microsoft.graph.orgContact",orgContactid: string,directoryObjectid: string):operation275,
(api:"/contacts/{orgContact-id}/memberOf/{directoryObject-id}/microsoft.graph.servicePrincipal",orgContactid: string,directoryObjectid: string):operation276,
(api:"/contacts/{orgContact-id}/memberOf/{directoryObject-id}/microsoft.graph.user",orgContactid: string,directoryObjectid: string):operation277,
(api:"/contacts/{orgContact-id}/memberOf/$count",orgContactid: string):operation278,
(api:"/contacts/{orgContact-id}/memberOf/microsoft.graph.application",orgContactid: string):operation279,
(api:"/contacts/{orgContact-id}/memberOf/microsoft.graph.application/$count",orgContactid: string):operation280,
(api:"/contacts/{orgContact-id}/memberOf/microsoft.graph.device",orgContactid: string):operation281,
(api:"/contacts/{orgContact-id}/memberOf/microsoft.graph.device/$count",orgContactid: string):operation282,
(api:"/contacts/{orgContact-id}/memberOf/microsoft.graph.group",orgContactid: string):operation283,
(api:"/contacts/{orgContact-id}/memberOf/microsoft.graph.group/$count",orgContactid: string):operation284,
(api:"/contacts/{orgContact-id}/memberOf/microsoft.graph.orgContact",orgContactid: string):operation285,
(api:"/contacts/{orgContact-id}/memberOf/microsoft.graph.orgContact/$count",orgContactid: string):operation286,
(api:"/contacts/{orgContact-id}/memberOf/microsoft.graph.servicePrincipal",orgContactid: string):operation287,
(api:"/contacts/{orgContact-id}/memberOf/microsoft.graph.servicePrincipal/$count",orgContactid: string):operation288,
(api:"/contacts/{orgContact-id}/memberOf/microsoft.graph.user",orgContactid: string):operation289,
(api:"/contacts/{orgContact-id}/memberOf/microsoft.graph.user/$count",orgContactid: string):operation290,
(api:"/contacts/{orgContact-id}/microsoft.graph.checkMemberGroups",orgContactid: string):operation291,
(api:"/contacts/{orgContact-id}/microsoft.graph.checkMemberObjects",orgContactid: string):operation292,
(api:"/contacts/{orgContact-id}/microsoft.graph.getMemberGroups",orgContactid: string):operation293,
(api:"/contacts/{orgContact-id}/microsoft.graph.getMemberObjects",orgContactid: string):operation294,
(api:"/contacts/{orgContact-id}/microsoft.graph.restore",orgContactid: string):operation295,
(api:"/contacts/{orgContact-id}/transitiveMemberOf",orgContactid: string):operation296,
(api:"/contacts/{orgContact-id}/transitiveMemberOf/{directoryObject-id}",orgContactid: string,directoryObjectid: string):operation297,
(api:"/contacts/{orgContact-id}/transitiveMemberOf/{directoryObject-id}/microsoft.graph.application",orgContactid: string,directoryObjectid: string):operation298,
(api:"/contacts/{orgContact-id}/transitiveMemberOf/{directoryObject-id}/microsoft.graph.device",orgContactid: string,directoryObjectid: string):operation299,
(api:"/contacts/{orgContact-id}/transitiveMemberOf/{directoryObject-id}/microsoft.graph.group",orgContactid: string,directoryObjectid: string):operation300,
(api:"/contacts/{orgContact-id}/transitiveMemberOf/{directoryObject-id}/microsoft.graph.orgContact",orgContactid: string,directoryObjectid: string):operation301,
(api:"/contacts/{orgContact-id}/transitiveMemberOf/{directoryObject-id}/microsoft.graph.servicePrincipal",orgContactid: string,directoryObjectid: string):operation302,
(api:"/contacts/{orgContact-id}/transitiveMemberOf/{directoryObject-id}/microsoft.graph.user",orgContactid: string,directoryObjectid: string):operation303,
(api:"/contacts/{orgContact-id}/transitiveMemberOf/$count",orgContactid: string):operation304,
(api:"/contacts/{orgContact-id}/transitiveMemberOf/microsoft.graph.application",orgContactid: string):operation305,
(api:"/contacts/{orgContact-id}/transitiveMemberOf/microsoft.graph.application/$count",orgContactid: string):operation306,
(api:"/contacts/{orgContact-id}/transitiveMemberOf/microsoft.graph.device",orgContactid: string):operation307,
(api:"/contacts/{orgContact-id}/transitiveMemberOf/microsoft.graph.device/$count",orgContactid: string):operation308,
(api:"/contacts/{orgContact-id}/transitiveMemberOf/microsoft.graph.group",orgContactid: string):operation309,
(api:"/contacts/{orgContact-id}/transitiveMemberOf/microsoft.graph.group/$count",orgContactid: string):operation310,
(api:"/contacts/{orgContact-id}/transitiveMemberOf/microsoft.graph.orgContact",orgContactid: string):operation311,
(api:"/contacts/{orgContact-id}/transitiveMemberOf/microsoft.graph.orgContact/$count",orgContactid: string):operation312,
(api:"/contacts/{orgContact-id}/transitiveMemberOf/microsoft.graph.servicePrincipal",orgContactid: string):operation313,
(api:"/contacts/{orgContact-id}/transitiveMemberOf/microsoft.graph.servicePrincipal/$count",orgContactid: string):operation314,
(api:"/contacts/{orgContact-id}/transitiveMemberOf/microsoft.graph.user",orgContactid: string):operation315,
(api:"/contacts/{orgContact-id}/transitiveMemberOf/microsoft.graph.user/$count",orgContactid: string):operation316,
(api:"/contacts/$count"):operation317,
(api:"/contacts/microsoft.graph.delta()"):operation318,
(api:"/contacts/microsoft.graph.getAvailableExtensionProperties"):operation319,
(api:"/contacts/microsoft.graph.getByIds"):operation320,
(api:"/contacts/microsoft.graph.validateProperties"):operation321,

