(api:"/security"):operation5138,
(api:"/security/alerts"):operation5139,
(api:"/security/alerts/{alert-id}",alertid: string):operation5140,
(api:"/security/alerts/$count"):operation5141,
(api:"/security/cases"):operation5142,
(api:"/security/cases/ediscoveryCases"):operation5143,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}",ediscoveryCaseid: string):operation5144,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/custodians",ediscoveryCaseid: string):operation5145,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/custodians/{ediscoveryCustodian-id}",ediscoveryCaseid: string,ediscoveryCustodianid: string):operation5146,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/custodians/{ediscoveryCustodian-id}/lastIndexOperation",ediscoveryCaseid: string,ediscoveryCustodianid: string):operation5147,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/custodians/{ediscoveryCustodian-id}/microsoft.graph.security.activate",ediscoveryCaseid: string,ediscoveryCustodianid: string):operation5148,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/custodians/{ediscoveryCustodian-id}/microsoft.graph.security.applyHold",ediscoveryCaseid: string,ediscoveryCustodianid: string):operation5149,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/custodians/{ediscoveryCustodian-id}/microsoft.graph.security.release",ediscoveryCaseid: string,ediscoveryCustodianid: string):operation5150,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/custodians/{ediscoveryCustodian-id}/microsoft.graph.security.removeHold",ediscoveryCaseid: string,ediscoveryCustodianid: string):operation5151,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/custodians/{ediscoveryCustodian-id}/microsoft.graph.security.updateIndex",ediscoveryCaseid: string,ediscoveryCustodianid: string):operation5152,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/custodians/{ediscoveryCustodian-id}/siteSources",ediscoveryCaseid: string,ediscoveryCustodianid: string):operation5153,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/custodians/{ediscoveryCustodian-id}/siteSources/{siteSource-id}",ediscoveryCaseid: string,ediscoveryCustodianid: string,siteSourceid: string):operation5154,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/custodians/{ediscoveryCustodian-id}/siteSources/{siteSource-id}/site",ediscoveryCaseid: string,ediscoveryCustodianid: string,siteSourceid: string):operation5155,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/custodians/{ediscoveryCustodian-id}/siteSources/$count",ediscoveryCaseid: string,ediscoveryCustodianid: string):operation5156,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/custodians/{ediscoveryCustodian-id}/unifiedGroupSources",ediscoveryCaseid: string,ediscoveryCustodianid: string):operation5157,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/custodians/{ediscoveryCustodian-id}/unifiedGroupSources/{unifiedGroupSource-id}",ediscoveryCaseid: string,ediscoveryCustodianid: string,unifiedGroupSourceid: string):operation5158,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/custodians/{ediscoveryCustodian-id}/unifiedGroupSources/{unifiedGroupSource-id}/group",ediscoveryCaseid: string,ediscoveryCustodianid: string,unifiedGroupSourceid: string):operation5159,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/custodians/{ediscoveryCustodian-id}/unifiedGroupSources/$count",ediscoveryCaseid: string,ediscoveryCustodianid: string):operation5160,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/custodians/{ediscoveryCustodian-id}/userSources",ediscoveryCaseid: string,ediscoveryCustodianid: string):operation5161,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/custodians/{ediscoveryCustodian-id}/userSources/{userSource-id}",ediscoveryCaseid: string,ediscoveryCustodianid: string,userSourceid: string):operation5162,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/custodians/{ediscoveryCustodian-id}/userSources/$count",ediscoveryCaseid: string,ediscoveryCustodianid: string):operation5163,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/custodians/$count",ediscoveryCaseid: string):operation5164,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/custodians/microsoft.graph.security.applyHold",ediscoveryCaseid: string):operation5165,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/custodians/microsoft.graph.security.removeHold",ediscoveryCaseid: string):operation5166,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/microsoft.graph.security.close",ediscoveryCaseid: string):operation5167,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/microsoft.graph.security.reopen",ediscoveryCaseid: string):operation5168,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/noncustodialDataSources",ediscoveryCaseid: string):operation5169,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/noncustodialDataSources/{ediscoveryNoncustodialDataSource-id}",ediscoveryCaseid: string,ediscoveryNoncustodialDataSourceid: string):operation5170,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/noncustodialDataSources/{ediscoveryNoncustodialDataSource-id}/dataSource",ediscoveryCaseid: string,ediscoveryNoncustodialDataSourceid: string):operation5171,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/noncustodialDataSources/{ediscoveryNoncustodialDataSource-id}/lastIndexOperation",ediscoveryCaseid: string,ediscoveryNoncustodialDataSourceid: string):operation5172,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/noncustodialDataSources/{ediscoveryNoncustodialDataSource-id}/microsoft.graph.security.applyHold",ediscoveryCaseid: string,ediscoveryNoncustodialDataSourceid: string):operation5173,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/noncustodialDataSources/{ediscoveryNoncustodialDataSource-id}/microsoft.graph.security.release",ediscoveryCaseid: string,ediscoveryNoncustodialDataSourceid: string):operation5174,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/noncustodialDataSources/{ediscoveryNoncustodialDataSource-id}/microsoft.graph.security.removeHold",ediscoveryCaseid: string,ediscoveryNoncustodialDataSourceid: string):operation5175,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/noncustodialDataSources/{ediscoveryNoncustodialDataSource-id}/microsoft.graph.security.updateIndex",ediscoveryCaseid: string,ediscoveryNoncustodialDataSourceid: string):operation5176,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/noncustodialDataSources/$count",ediscoveryCaseid: string):operation5177,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/noncustodialDataSources/microsoft.graph.security.applyHold",ediscoveryCaseid: string):operation5178,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/noncustodialDataSources/microsoft.graph.security.removeHold",ediscoveryCaseid: string):operation5179,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/operations",ediscoveryCaseid: string):operation5180,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/operations/{caseOperation-id}",ediscoveryCaseid: string,caseOperationid: string):operation5181,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/operations/$count",ediscoveryCaseid: string):operation5182,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/reviewSets",ediscoveryCaseid: string):operation5183,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/reviewSets/{ediscoveryReviewSet-id}",ediscoveryCaseid: string,ediscoveryReviewSetid: string):operation5184,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/reviewSets/{ediscoveryReviewSet-id}/microsoft.graph.security.addToReviewSet",ediscoveryCaseid: string,ediscoveryReviewSetid: string):operation5185,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/reviewSets/{ediscoveryReviewSet-id}/queries",ediscoveryCaseid: string,ediscoveryReviewSetid: string):operation5186,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/reviewSets/{ediscoveryReviewSet-id}/queries/{ediscoveryReviewSetQuery-id}",ediscoveryCaseid: string,ediscoveryReviewSetid: string,ediscoveryReviewSetQueryid: string):operation5187,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/reviewSets/{ediscoveryReviewSet-id}/queries/{ediscoveryReviewSetQuery-id}/microsoft.graph.security.applyTags",ediscoveryCaseid: string,ediscoveryReviewSetid: string,ediscoveryReviewSetQueryid: string):operation5188,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/reviewSets/{ediscoveryReviewSet-id}/queries/$count",ediscoveryCaseid: string,ediscoveryReviewSetid: string):operation5189,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/reviewSets/$count",ediscoveryCaseid: string):operation5190,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/searches",ediscoveryCaseid: string):operation5191,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/searches/{ediscoverySearch-id}",ediscoveryCaseid: string,ediscoverySearchid: string):operation5192,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/searches/{ediscoverySearch-id}/additionalSources",ediscoveryCaseid: string,ediscoverySearchid: string):operation5193,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/searches/{ediscoverySearch-id}/additionalSources/{dataSource-id}",ediscoveryCaseid: string,ediscoverySearchid: string,dataSourceid: string):operation5194,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/searches/{ediscoverySearch-id}/additionalSources/$count",ediscoveryCaseid: string,ediscoverySearchid: string):operation5195,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/searches/{ediscoverySearch-id}/addToReviewSetOperation",ediscoveryCaseid: string,ediscoverySearchid: string):operation5196,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/searches/{ediscoverySearch-id}/custodianSources",ediscoveryCaseid: string,ediscoverySearchid: string):operation5197,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/searches/{ediscoverySearch-id}/custodianSources/{dataSource-id}",ediscoveryCaseid: string,ediscoverySearchid: string,dataSourceid: string):operation5198,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/searches/{ediscoverySearch-id}/custodianSources/$count",ediscoveryCaseid: string,ediscoverySearchid: string):operation5199,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/searches/{ediscoverySearch-id}/lastEstimateStatisticsOperation",ediscoveryCaseid: string,ediscoverySearchid: string):operation5200,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/searches/{ediscoverySearch-id}/microsoft.graph.security.estimateStatistics",ediscoveryCaseid: string,ediscoverySearchid: string):operation5201,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/searches/{ediscoverySearch-id}/noncustodialSources",ediscoveryCaseid: string,ediscoverySearchid: string):operation5202,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/searches/{ediscoverySearch-id}/noncustodialSources/{ediscoveryNoncustodialDataSource-id}",ediscoveryCaseid: string,ediscoverySearchid: string,ediscoveryNoncustodialDataSourceid: string):operation5203,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/searches/{ediscoverySearch-id}/noncustodialSources/$count",ediscoveryCaseid: string,ediscoverySearchid: string):operation5204,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/searches/$count",ediscoveryCaseid: string):operation5205,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/settings",ediscoveryCaseid: string):operation5206,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/settings/microsoft.graph.security.resetToDefault",ediscoveryCaseid: string):operation5207,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/tags",ediscoveryCaseid: string):operation5208,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/tags/{ediscoveryReviewTag-id}",ediscoveryCaseid: string,ediscoveryReviewTagid: string):operation5209,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/tags/{ediscoveryReviewTag-id}/childTags",ediscoveryCaseid: string,ediscoveryReviewTagid: string):operation5210,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/tags/{ediscoveryReviewTag-id}/childTags/{ediscoveryReviewTag-id1}",ediscoveryCaseid: string,ediscoveryReviewTagid: string,ediscoveryReviewTagid1: string):operation5211,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/tags/{ediscoveryReviewTag-id}/childTags/$count",ediscoveryCaseid: string,ediscoveryReviewTagid: string):operation5212,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/tags/{ediscoveryReviewTag-id}/parent",ediscoveryCaseid: string,ediscoveryReviewTagid: string):operation5213,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/tags/$count",ediscoveryCaseid: string):operation5214,
(api:"/security/cases/ediscoveryCases/{ediscoveryCase-id}/tags/microsoft.graph.security.asHierarchy()",ediscoveryCaseid: string):operation5215,
(api:"/security/cases/ediscoveryCases/$count"):operation5216,
(api:"/security/secureScoreControlProfiles"):operation5217,
(api:"/security/secureScoreControlProfiles/{secureScoreControlProfile-id}",secureScoreControlProfileid: string):operation5218,
(api:"/security/secureScoreControlProfiles/$count"):operation5219,
(api:"/security/secureScores"):operation5220,
(api:"/security/secureScores/{secureScore-id}",secureScoreid: string):operation5221,
(api:"/security/secureScores/$count"):operation5222,