(api:"/groups/{group-id}/planner",groupid: string):operation2113,
    (api:"/groups/{group-id}/planner/plans",groupid: string):operation2114,
    (api:"/groups/{group-id}/planner/plans/{plannerPlan-id}",groupid: string,plannerPlanid: string):operation2115,
    (api:"/groups/{group-id}/planner/plans/{plannerPlan-id}/buckets",groupid: string,plannerPlanid: string):operation2116,
    (api:"/groups/{group-id}/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}",groupid: string,plannerPlanid: string,plannerBucketid: string):operation2117,
    (api:"/groups/{group-id}/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks",groupid: string,plannerPlanid: string,plannerBucketid: string):operation2118,
    (api:"/groups/{group-id}/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks/{plannerTask-id}",groupid: string,plannerPlanid: string,plannerBucketid: string,plannerTaskid: string):operation2119,
    (api:"/groups/{group-id}/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks/{plannerTask-id}/assignedToTaskBoardFormat",groupid: string,plannerPlanid: string,plannerBucketid: string,plannerTaskid: string):operation2120,
    (api:"/groups/{group-id}/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks/{plannerTask-id}/bucketTaskBoardFormat",groupid: string,plannerPlanid: string,plannerBucketid: string,plannerTaskid: string):operation2121,
    (api:"/groups/{group-id}/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks/{plannerTask-id}/details",groupid: string,plannerPlanid: string,plannerBucketid: string,plannerTaskid: string):operation2122,
    (api:"/groups/{group-id}/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks/{plannerTask-id}/progressTaskBoardFormat",groupid: string,plannerPlanid: string,plannerBucketid: string,plannerTaskid: string):operation2123,
    (api:"/groups/{group-id}/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks/$count",groupid: string,plannerPlanid: string,plannerBucketid: string):operation2124,
    (api:"/groups/{group-id}/planner/plans/{plannerPlan-id}/buckets/$count",groupid: string,plannerPlanid: string):operation2125,
    (api:"/groups/{group-id}/planner/plans/{plannerPlan-id}/details",groupid: string,plannerPlanid: string):operation2126,
    (api:"/groups/{group-id}/planner/plans/{plannerPlan-id}/tasks",groupid: string,plannerPlanid: string):operation2127,
    (api:"/groups/{group-id}/planner/plans/{plannerPlan-id}/tasks/{plannerTask-id}",groupid: string,plannerPlanid: string,plannerTaskid: string):operation2128,
    (api:"/groups/{group-id}/planner/plans/{plannerPlan-id}/tasks/{plannerTask-id}/assignedToTaskBoardFormat",groupid: string,plannerPlanid: string,plannerTaskid: string):operation2129,
    (api:"/groups/{group-id}/planner/plans/{plannerPlan-id}/tasks/{plannerTask-id}/bucketTaskBoardFormat",groupid: string,plannerPlanid: string,plannerTaskid: string):operation2130,
    (api:"/groups/{group-id}/planner/plans/{plannerPlan-id}/tasks/{plannerTask-id}/details",groupid: string,plannerPlanid: string,plannerTaskid: string):operation2131,
    (api:"/groups/{group-id}/planner/plans/{plannerPlan-id}/tasks/{plannerTask-id}/progressTaskBoardFormat",groupid: string,plannerPlanid: string,plannerTaskid: string):operation2132,
    (api:"/groups/{group-id}/planner/plans/{plannerPlan-id}/tasks/$count",groupid: string,plannerPlanid: string):operation2133,
    (api:"/groups/{group-id}/planner/plans/$count",groupid: string):operation2134,

    (api:"/me/planner"):operation4597,
    (api:"/me/planner/plans"):operation4598,
    (api:"/me/planner/plans/{plannerPlan-id}",plannerPlanid: string):operation4599,
    (api:"/me/planner/plans/{plannerPlan-id}/buckets",plannerPlanid: string):operation4600,
    (api:"/me/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}",plannerPlanid: string,plannerBucketid: string):operation4601,
    (api:"/me/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks",plannerPlanid: string,plannerBucketid: string):operation4602,
    (api:"/me/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks/{plannerTask-id}",plannerPlanid: string,plannerBucketid: string,plannerTaskid: string):operation4603,
    (api:"/me/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks/{plannerTask-id}/assignedToTaskBoardFormat",plannerPlanid: string,plannerBucketid: string,plannerTaskid: string):operation4604,
    (api:"/me/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks/{plannerTask-id}/bucketTaskBoardFormat",plannerPlanid: string,plannerBucketid: string,plannerTaskid: string):operation4605,
    (api:"/me/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks/{plannerTask-id}/details",plannerPlanid: string,plannerBucketid: string,plannerTaskid: string):operation4606,
    (api:"/me/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks/{plannerTask-id}/progressTaskBoardFormat",plannerPlanid: string,plannerBucketid: string,plannerTaskid: string):operation4607,
    (api:"/me/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks/$count",plannerPlanid: string,plannerBucketid: string):operation4608,
    (api:"/me/planner/plans/{plannerPlan-id}/buckets/$count",plannerPlanid: string):operation4609,
    (api:"/me/planner/plans/{plannerPlan-id}/details",plannerPlanid: string):operation4610,
    (api:"/me/planner/plans/{plannerPlan-id}/tasks",plannerPlanid: string):operation4611,
    (api:"/me/planner/plans/{plannerPlan-id}/tasks/{plannerTask-id}",plannerPlanid: string,plannerTaskid: string):operation4612,
    (api:"/me/planner/plans/{plannerPlan-id}/tasks/{plannerTask-id}/assignedToTaskBoardFormat",plannerPlanid: string,plannerTaskid: string):operation4613,
    (api:"/me/planner/plans/{plannerPlan-id}/tasks/{plannerTask-id}/bucketTaskBoardFormat",plannerPlanid: string,plannerTaskid: string):operation4614,
    (api:"/me/planner/plans/{plannerPlan-id}/tasks/{plannerTask-id}/details",plannerPlanid: string,plannerTaskid: string):operation4615,
    (api:"/me/planner/plans/{plannerPlan-id}/tasks/{plannerTask-id}/progressTaskBoardFormat",plannerPlanid: string,plannerTaskid: string):operation4616,
    (api:"/me/planner/plans/{plannerPlan-id}/tasks/$count",plannerPlanid: string):operation4617,
    (api:"/me/planner/plans/$count"):operation4618,
    (api:"/me/planner/tasks"):operation4619,
    (api:"/me/planner/tasks/{plannerTask-id}",plannerTaskid: string):operation4620,
    (api:"/me/planner/tasks/{plannerTask-id}/assignedToTaskBoardFormat",plannerTaskid: string):operation4621,
    (api:"/me/planner/tasks/{plannerTask-id}/bucketTaskBoardFormat",plannerTaskid: string):operation4622,
    (api:"/me/planner/tasks/{plannerTask-id}/details",plannerTaskid: string):operation4623,
    (api:"/me/planner/tasks/{plannerTask-id}/progressTaskBoardFormat",plannerTaskid: string):operation4624,
    (api:"/me/planner/tasks/$count"):operation4625,


    (api:"/planner"):operation4756,
    (api:"/planner/buckets"):operation4757,
    (api:"/planner/buckets/{plannerBucket-id}",plannerBucketid: string):operation4758,
    (api:"/planner/buckets/{plannerBucket-id}/tasks",plannerBucketid: string):operation4759,
    (api:"/planner/buckets/{plannerBucket-id}/tasks/{plannerTask-id}",plannerBucketid: string,plannerTaskid: string):operation4760,
    (api:"/planner/buckets/{plannerBucket-id}/tasks/{plannerTask-id}/assignedToTaskBoardFormat",plannerBucketid: string,plannerTaskid: string):operation4761,
    (api:"/planner/buckets/{plannerBucket-id}/tasks/{plannerTask-id}/bucketTaskBoardFormat",plannerBucketid: string,plannerTaskid: string):operation4762,
    (api:"/planner/buckets/{plannerBucket-id}/tasks/{plannerTask-id}/details",plannerBucketid: string,plannerTaskid: string):operation4763,
    (api:"/planner/buckets/{plannerBucket-id}/tasks/{plannerTask-id}/progressTaskBoardFormat",plannerBucketid: string,plannerTaskid: string):operation4764,
    (api:"/planner/buckets/{plannerBucket-id}/tasks/$count",plannerBucketid: string):operation4765,
    (api:"/planner/buckets/$count"):operation4766,
    (api:"/planner/plans"):operation4767,
    (api:"/planner/plans/{plannerPlan-id}",plannerPlanid: string):operation4768,
    (api:"/planner/plans/{plannerPlan-id}/buckets",plannerPlanid: string):operation4769,
    (api:"/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}",plannerPlanid: string,plannerBucketid: string):operation4770,
    (api:"/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks",plannerPlanid: string,plannerBucketid: string):operation4771,
    (api:"/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks/{plannerTask-id}",plannerPlanid: string,plannerBucketid: string,plannerTaskid: string):operation4772,
    (api:"/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks/{plannerTask-id}/assignedToTaskBoardFormat",plannerPlanid: string,plannerBucketid: string,plannerTaskid: string):operation4773,
    (api:"/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks/{plannerTask-id}/bucketTaskBoardFormat",plannerPlanid: string,plannerBucketid: string,plannerTaskid: string):operation4774,
    (api:"/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks/{plannerTask-id}/details",plannerPlanid: string,plannerBucketid: string,plannerTaskid: string):operation4775,
    (api:"/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks/{plannerTask-id}/progressTaskBoardFormat",plannerPlanid: string,plannerBucketid: string,plannerTaskid: string):operation4776,
    (api:"/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks/$count",plannerPlanid: string,plannerBucketid: string):operation4777,
    (api:"/planner/plans/{plannerPlan-id}/buckets/$count",plannerPlanid: string):operation4778,
    (api:"/planner/plans/{plannerPlan-id}/details",plannerPlanid: string):operation4779,
    (api:"/planner/plans/{plannerPlan-id}/tasks",plannerPlanid: string):operation4780,
    (api:"/planner/plans/{plannerPlan-id}/tasks/{plannerTask-id}",plannerPlanid: string,plannerTaskid: string):operation4781,
    (api:"/planner/plans/{plannerPlan-id}/tasks/{plannerTask-id}/assignedToTaskBoardFormat",plannerPlanid: string,plannerTaskid: string):operation4782,
    (api:"/planner/plans/{plannerPlan-id}/tasks/{plannerTask-id}/bucketTaskBoardFormat",plannerPlanid: string,plannerTaskid: string):operation4783,
    (api:"/planner/plans/{plannerPlan-id}/tasks/{plannerTask-id}/details",plannerPlanid: string,plannerTaskid: string):operation4784,
    (api:"/planner/plans/{plannerPlan-id}/tasks/{plannerTask-id}/progressTaskBoardFormat",plannerPlanid: string,plannerTaskid: string):operation4785,
    (api:"/planner/plans/{plannerPlan-id}/tasks/$count",plannerPlanid: string):operation4786,
    (api:"/planner/plans/$count"):operation4787,
    (api:"/planner/tasks"):operation4788,
    (api:"/planner/tasks/{plannerTask-id}",plannerTaskid: string):operation4789,
    (api:"/planner/tasks/{plannerTask-id}/assignedToTaskBoardFormat",plannerTaskid: string):operation4790,
    (api:"/planner/tasks/{plannerTask-id}/bucketTaskBoardFormat",plannerTaskid: string):operation4791,
    (api:"/planner/tasks/{plannerTask-id}/details",plannerTaskid: string):operation4792,
    (api:"/planner/tasks/{plannerTask-id}/progressTaskBoardFormat",plannerTaskid: string):operation4793,
    (api:"/planner/tasks/$count"):operation4794,

    (api:"/users/{user-id}/planner",userid: string):operation7610,
    (api:"/users/{user-id}/planner/plans",userid: string):operation7611,
    (api:"/users/{user-id}/planner/plans/{plannerPlan-id}",userid: string,plannerPlanid: string):operation7612,
    (api:"/users/{user-id}/planner/plans/{plannerPlan-id}/buckets",userid: string,plannerPlanid: string):operation7613,
    (api:"/users/{user-id}/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}",userid: string,plannerPlanid: string,plannerBucketid: string):operation7614,
    (api:"/users/{user-id}/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks",userid: string,plannerPlanid: string,plannerBucketid: string):operation7615,
    (api:"/users/{user-id}/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks/{plannerTask-id}",userid: string,plannerPlanid: string,plannerBucketid: string,plannerTaskid: string):operation7616,
    (api:"/users/{user-id}/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks/{plannerTask-id}/assignedToTaskBoardFormat",userid: string,plannerPlanid: string,plannerBucketid: string,plannerTaskid: string):operation7617,
    (api:"/users/{user-id}/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks/{plannerTask-id}/bucketTaskBoardFormat",userid: string,plannerPlanid: string,plannerBucketid: string,plannerTaskid: string):operation7618,
    (api:"/users/{user-id}/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks/{plannerTask-id}/details",userid: string,plannerPlanid: string,plannerBucketid: string,plannerTaskid: string):operation7619,
    (api:"/users/{user-id}/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks/{plannerTask-id}/progressTaskBoardFormat",userid: string,plannerPlanid: string,plannerBucketid: string,plannerTaskid: string):operation7620,
    (api:"/users/{user-id}/planner/plans/{plannerPlan-id}/buckets/{plannerBucket-id}/tasks/$count",userid: string,plannerPlanid: string,plannerBucketid: string):operation7621,
    (api:"/users/{user-id}/planner/plans/{plannerPlan-id}/buckets/$count",userid: string,plannerPlanid: string):operation7622,
    (api:"/users/{user-id}/planner/plans/{plannerPlan-id}/details",userid: string,plannerPlanid: string):operation7623,
    (api:"/users/{user-id}/planner/plans/{plannerPlan-id}/tasks",userid: string,plannerPlanid: string):operation7624,
    (api:"/users/{user-id}/planner/plans/{plannerPlan-id}/tasks/{plannerTask-id}",userid: string,plannerPlanid: string,plannerTaskid: string):operation7625,
    (api:"/users/{user-id}/planner/plans/{plannerPlan-id}/tasks/{plannerTask-id}/assignedToTaskBoardFormat",userid: string,plannerPlanid: string,plannerTaskid: string):operation7626,
    (api:"/users/{user-id}/planner/plans/{plannerPlan-id}/tasks/{plannerTask-id}/bucketTaskBoardFormat",userid: string,plannerPlanid: string,plannerTaskid: string):operation7627,
    (api:"/users/{user-id}/planner/plans/{plannerPlan-id}/tasks/{plannerTask-id}/details",userid: string,plannerPlanid: string,plannerTaskid: string):operation7628,
    (api:"/users/{user-id}/planner/plans/{plannerPlan-id}/tasks/{plannerTask-id}/progressTaskBoardFormat",userid: string,plannerPlanid: string,plannerTaskid: string):operation7629,
    (api:"/users/{user-id}/planner/plans/{plannerPlan-id}/tasks/$count",userid: string,plannerPlanid: string):operation7630,
    (api:"/users/{user-id}/planner/plans/$count",userid: string):operation7631,
    (api:"/users/{user-id}/planner/tasks",userid: string):operation7632,
    (api:"/users/{user-id}/planner/tasks/{plannerTask-id}",userid: string,plannerTaskid: string):operation7633,
    (api:"/users/{user-id}/planner/tasks/{plannerTask-id}/assignedToTaskBoardFormat",userid: string,plannerTaskid: string):operation7634,
    (api:"/users/{user-id}/planner/tasks/{plannerTask-id}/bucketTaskBoardFormat",userid: string,plannerTaskid: string):operation7635,
    (api:"/users/{user-id}/planner/tasks/{plannerTask-id}/details",userid: string,plannerTaskid: string):operation7636,
    (api:"/users/{user-id}/planner/tasks/{plannerTask-id}/progressTaskBoardFormat",userid: string,plannerTaskid: string):operation7637,
    (api:"/users/{user-id}/planner/tasks/$count",userid: string):operation7638,