(api:"/teams"):operation6003,
(api:"/teams/{team-id}",teamid: string):operation6004,
(api:"/teams/{team-id}/allChannels",teamid: string):operation6005,
(api:"/teams/{team-id}/allChannels/{channel-id}",teamid: string,channelid: string):operation6006,
(api:"/teams/{team-id}/allChannels/$count",teamid: string):operation6007,
(api:"/teams/{team-id}/channels",teamid: string):operation6008,
(api:"/teams/{team-id}/channels/{channel-id}",teamid: string,channelid: string):operation6009,
(api:"/teams/{team-id}/channels/{channel-id}/filesFolder",teamid: string,channelid: string):operation6010,
(api:"/teams/{team-id}/channels/{channel-id}/filesFolder/content",teamid: string,channelid: string):operation6011,
(api:"/teams/{team-id}/channels/{channel-id}/members",teamid: string,channelid: string):operation6012,
(api:"/teams/{team-id}/channels/{channel-id}/members/{conversationMember-id}",teamid: string,channelid: string,conversationMemberid: string):operation6013,
(api:"/teams/{team-id}/channels/{channel-id}/members/$count",teamid: string,channelid: string):operation6014,
(api:"/teams/{team-id}/channels/{channel-id}/members/microsoft.graph.add",teamid: string,channelid: string):operation6015,
(api:"/teams/{team-id}/channels/{channel-id}/messages",teamid: string,channelid: string):operation6016,
(api:"/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}",teamid: string,channelid: string,chatMessageid: string):operation6017,
(api:"/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/hostedContents",teamid: string,channelid: string,chatMessageid: string):operation6018,
(api:"/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/hostedContents/{chatMessageHostedContent-id}",teamid: string,channelid: string,chatMessageid: string,chatMessageHostedContentid: string):operation6019,
(api:"/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/hostedContents/$count",teamid: string,channelid: string,chatMessageid: string):operation6020,
(api:"/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies",teamid: string,channelid: string,chatMessageid: string):operation6021,
(api:"/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}",teamid: string,channelid: string,chatMessageid: string,chatMessageid1: string):operation6022,
(api:"/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents",teamid: string,channelid: string,chatMessageid: string,chatMessageid1: string):operation6023,
(api:"/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/{chatMessageHostedContent-id}",teamid: string,channelid: string,chatMessageid: string,chatMessageid1: string,chatMessageHostedContentid: string):operation6024,
(api:"/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/$count",teamid: string,channelid: string,chatMessageid: string,chatMessageid1: string):operation6025,
(api:"/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/$count",teamid: string,channelid: string,chatMessageid: string):operation6026,
(api:"/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/microsoft.graph.delta()",teamid: string,channelid: string,chatMessageid: string):operation6027,
(api:"/teams/{team-id}/channels/{channel-id}/messages/$count",teamid: string,channelid: string):operation6028,
(api:"/teams/{team-id}/channels/{channel-id}/messages/microsoft.graph.delta()",teamid: string,channelid: string):operation6029,
(api:"/teams/{team-id}/channels/{channel-id}/microsoft.graph.completeMigration",teamid: string,channelid: string):operation6030,
(api:"/teams/{team-id}/channels/{channel-id}/microsoft.graph.doesUserHaveAccess(userId='{userId}',tenantId='{tenantId}',userPrincipalName='{userPrincipalName}')",teamid: string,channelid: string,userId: string,tenantId: string,userPrincipalName: string):operation6031,
(api:"/teams/{team-id}/channels/{channel-id}/microsoft.graph.provisionEmail",teamid: string,channelid: string):operation6032,
(api:"/teams/{team-id}/channels/{channel-id}/microsoft.graph.removeEmail",teamid: string,channelid: string):operation6033,
(api:"/teams/{team-id}/channels/{channel-id}/sharedWithTeams",teamid: string,channelid: string):operation6034,
(api:"/teams/{team-id}/channels/{channel-id}/sharedWithTeams/{sharedWithChannelTeamInfo-id}",teamid: string,channelid: string,sharedWithChannelTeamInfoid: string):operation6035,
(api:"/teams/{team-id}/channels/{channel-id}/sharedWithTeams/{sharedWithChannelTeamInfo-id}/allowedMembers",teamid: string,channelid: string,sharedWithChannelTeamInfoid: string):operation6036,
(api:"/teams/{team-id}/channels/{channel-id}/sharedWithTeams/{sharedWithChannelTeamInfo-id}/allowedMembers/{conversationMember-id}",teamid: string,channelid: string,sharedWithChannelTeamInfoid: string,conversationMemberid: string):operation6037,
(api:"/teams/{team-id}/channels/{channel-id}/sharedWithTeams/{sharedWithChannelTeamInfo-id}/allowedMembers/$count",teamid: string,channelid: string,sharedWithChannelTeamInfoid: string):operation6038,
(api:"/teams/{team-id}/channels/{channel-id}/sharedWithTeams/$count",teamid: string,channelid: string):operation6039,
(api:"/teams/{team-id}/channels/{channel-id}/tabs",teamid: string,channelid: string):operation6040,
(api:"/teams/{team-id}/channels/{channel-id}/tabs/{teamsTab-id}",teamid: string,channelid: string,teamsTabid: string):operation6041,
(api:"/teams/{team-id}/channels/{channel-id}/tabs/{teamsTab-id}/teamsApp",teamid: string,channelid: string,teamsTabid: string):operation6042,
(api:"/teams/{team-id}/channels/{channel-id}/tabs/$count",teamid: string,channelid: string):operation6043,
(api:"/teams/{team-id}/channels/$count",teamid: string):operation6044,
(api:"/teams/{team-id}/channels/microsoft.graph.getAllMessages()",teamid: string):operation6045,
(api:"/teams/{team-id}/group",teamid: string):operation6046,
(api:"/teams/{team-id}/incomingChannels",teamid: string):operation6047,
(api:"/teams/{team-id}/incomingChannels/{channel-id}",teamid: string,channelid: string):operation6048,
(api:"/teams/{team-id}/incomingChannels/$count",teamid: string):operation6049,
(api:"/teams/{team-id}/installedApps",teamid: string):operation6050,
(api:"/teams/{team-id}/installedApps/{teamsAppInstallation-id}",teamid: string,teamsAppInstallationid: string):operation6051,
(api:"/teams/{team-id}/installedApps/{teamsAppInstallation-id}/microsoft.graph.upgrade",teamid: string,teamsAppInstallationid: string):operation6052,
(api:"/teams/{team-id}/installedApps/{teamsAppInstallation-id}/teamsApp",teamid: string,teamsAppInstallationid: string):operation6053,
(api:"/teams/{team-id}/installedApps/{teamsAppInstallation-id}/teamsAppDefinition",teamid: string,teamsAppInstallationid: string):operation6054,
(api:"/teams/{team-id}/installedApps/$count",teamid: string):operation6055,
(api:"/teams/{team-id}/members",teamid: string):operation6056,
(api:"/teams/{team-id}/members/{conversationMember-id}",teamid: string,conversationMemberid: string):operation6057,
(api:"/teams/{team-id}/members/$count",teamid: string):operation6058,
(api:"/teams/{team-id}/members/microsoft.graph.add",teamid: string):operation6059,
(api:"/teams/{team-id}/microsoft.graph.archive",teamid: string):operation6060,
(api:"/teams/{team-id}/microsoft.graph.clone",teamid: string):operation6061,
(api:"/teams/{team-id}/microsoft.graph.completeMigration",teamid: string):operation6062,
(api:"/teams/{team-id}/microsoft.graph.sendActivityNotification",teamid: string):operation6063,
(api:"/teams/{team-id}/microsoft.graph.unarchive",teamid: string):operation6064,
(api:"/teams/{team-id}/operations",teamid: string):operation6065,
(api:"/teams/{team-id}/operations/{teamsAsyncOperation-id}",teamid: string,teamsAsyncOperationid: string):operation6066,
(api:"/teams/{team-id}/operations/$count",teamid: string):operation6067,
(api:"/teams/{team-id}/photo",teamid: string):operation6068,
(api:"/teams/{team-id}/photo/$value",teamid: string):operation6069,
(api:"/teams/{team-id}/primaryChannel",teamid: string):operation6070,
(api:"/teams/{team-id}/primaryChannel/filesFolder",teamid: string):operation6071,
(api:"/teams/{team-id}/primaryChannel/filesFolder/content",teamid: string):operation6072,
(api:"/teams/{team-id}/primaryChannel/members",teamid: string):operation6073,
(api:"/teams/{team-id}/primaryChannel/members/{conversationMember-id}",teamid: string,conversationMemberid: string):operation6074,
(api:"/teams/{team-id}/primaryChannel/members/$count",teamid: string):operation6075,
(api:"/teams/{team-id}/primaryChannel/members/microsoft.graph.add",teamid: string):operation6076,
(api:"/teams/{team-id}/primaryChannel/messages",teamid: string):operation6077,
(api:"/teams/{team-id}/primaryChannel/messages/{chatMessage-id}",teamid: string,chatMessageid: string):operation6078,
(api:"/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/hostedContents",teamid: string,chatMessageid: string):operation6079,
(api:"/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/hostedContents/{chatMessageHostedContent-id}",teamid: string,chatMessageid: string,chatMessageHostedContentid: string):operation6080,
(api:"/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/hostedContents/$count",teamid: string,chatMessageid: string):operation6081,
(api:"/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies",teamid: string,chatMessageid: string):operation6082,
(api:"/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies/{chatMessage-id1}",teamid: string,chatMessageid: string,chatMessageid1: string):operation6083,
(api:"/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents",teamid: string,chatMessageid: string,chatMessageid1: string):operation6084,
(api:"/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/{chatMessageHostedContent-id}",teamid: string,chatMessageid: string,chatMessageid1: string,chatMessageHostedContentid: string):operation6085,
(api:"/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/$count",teamid: string,chatMessageid: string,chatMessageid1: string):operation6086,
(api:"/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies/$count",teamid: string,chatMessageid: string):operation6087,
(api:"/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies/microsoft.graph.delta()",teamid: string,chatMessageid: string):operation6088,
(api:"/teams/{team-id}/primaryChannel/messages/$count",teamid: string):operation6089,
(api:"/teams/{team-id}/primaryChannel/messages/microsoft.graph.delta()",teamid: string):operation6090,
(api:"/teams/{team-id}/primaryChannel/microsoft.graph.completeMigration",teamid: string):operation6091,
(api:"/teams/{team-id}/primaryChannel/microsoft.graph.doesUserHaveAccess(userId='{userId}',tenantId='{tenantId}',userPrincipalName='{userPrincipalName}')",teamid: string,userId: string,tenantId: string,userPrincipalName: string):operation6092,
(api:"/teams/{team-id}/primaryChannel/microsoft.graph.provisionEmail",teamid: string):operation6093,
(api:"/teams/{team-id}/primaryChannel/microsoft.graph.removeEmail",teamid: string):operation6094,
(api:"/teams/{team-id}/primaryChannel/sharedWithTeams",teamid: string):operation6095,
(api:"/teams/{team-id}/primaryChannel/sharedWithTeams/{sharedWithChannelTeamInfo-id}",teamid: string,sharedWithChannelTeamInfoid: string):operation6096,
(api:"/teams/{team-id}/primaryChannel/sharedWithTeams/{sharedWithChannelTeamInfo-id}/allowedMembers",teamid: string,sharedWithChannelTeamInfoid: string):operation6097,
(api:"/teams/{team-id}/primaryChannel/sharedWithTeams/{sharedWithChannelTeamInfo-id}/allowedMembers/{conversationMember-id}",teamid: string,sharedWithChannelTeamInfoid: string,conversationMemberid: string):operation6098,
(api:"/teams/{team-id}/primaryChannel/sharedWithTeams/{sharedWithChannelTeamInfo-id}/allowedMembers/$count",teamid: string,sharedWithChannelTeamInfoid: string):operation6099,
(api:"/teams/{team-id}/primaryChannel/sharedWithTeams/$count",teamid: string):operation6100,
(api:"/teams/{team-id}/primaryChannel/tabs",teamid: string):operation6101,
(api:"/teams/{team-id}/primaryChannel/tabs/{teamsTab-id}",teamid: string,teamsTabid: string):operation6102,
(api:"/teams/{team-id}/primaryChannel/tabs/{teamsTab-id}/teamsApp",teamid: string,teamsTabid: string):operation6103,
(api:"/teams/{team-id}/primaryChannel/tabs/$count",teamid: string):operation6104,
(api:"/teams/{team-id}/schedule",teamid: string):operation6105,
(api:"/teams/{team-id}/schedule/microsoft.graph.share",teamid: string):operation6106,
(api:"/teams/{team-id}/schedule/offerShiftRequests",teamid: string):operation6107,
(api:"/teams/{team-id}/schedule/offerShiftRequests/{offerShiftRequest-id}",teamid: string,offerShiftRequestid: string):operation6108,
(api:"/teams/{team-id}/schedule/offerShiftRequests/$count",teamid: string):operation6109,
(api:"/teams/{team-id}/schedule/openShiftChangeRequests",teamid: string):operation6110,
(api:"/teams/{team-id}/schedule/openShiftChangeRequests/{openShiftChangeRequest-id}",teamid: string,openShiftChangeRequestid: string):operation6111,
(api:"/teams/{team-id}/schedule/openShiftChangeRequests/$count",teamid: string):operation6112,
(api:"/teams/{team-id}/schedule/openShifts",teamid: string):operation6113,
(api:"/teams/{team-id}/schedule/openShifts/{openShift-id}",teamid: string,openShiftid: string):operation6114,
(api:"/teams/{team-id}/schedule/openShifts/$count",teamid: string):operation6115,
(api:"/teams/{team-id}/schedule/schedulingGroups",teamid: string):operation6116,
(api:"/teams/{team-id}/schedule/schedulingGroups/{schedulingGroup-id}",teamid: string,schedulingGroupid: string):operation6117,
(api:"/teams/{team-id}/schedule/schedulingGroups/$count",teamid: string):operation6118,
(api:"/teams/{team-id}/schedule/shifts",teamid: string):operation6119,
(api:"/teams/{team-id}/schedule/shifts/{shift-id}",teamid: string,shiftid: string):operation6120,
(api:"/teams/{team-id}/schedule/shifts/$count",teamid: string):operation6121,
(api:"/teams/{team-id}/schedule/swapShiftsChangeRequests",teamid: string):operation6122,
(api:"/teams/{team-id}/schedule/swapShiftsChangeRequests/{swapShiftsChangeRequest-id}",teamid: string,swapShiftsChangeRequestid: string):operation6123,
(api:"/teams/{team-id}/schedule/swapShiftsChangeRequests/$count",teamid: string):operation6124,
(api:"/teams/{team-id}/schedule/timeOffReasons",teamid: string):operation6125,
(api:"/teams/{team-id}/schedule/timeOffReasons/{timeOffReason-id}",teamid: string,timeOffReasonid: string):operation6126,
(api:"/teams/{team-id}/schedule/timeOffReasons/$count",teamid: string):operation6127,
(api:"/teams/{team-id}/schedule/timeOffRequests",teamid: string):operation6128,
(api:"/teams/{team-id}/schedule/timeOffRequests/{timeOffRequest-id}",teamid: string,timeOffRequestid: string):operation6129,
(api:"/teams/{team-id}/schedule/timeOffRequests/$count",teamid: string):operation6130,
(api:"/teams/{team-id}/schedule/timesOff",teamid: string):operation6131,
(api:"/teams/{team-id}/schedule/timesOff/{timeOff-id}",teamid: string,timeOffid: string):operation6132,
(api:"/teams/{team-id}/schedule/timesOff/$count",teamid: string):operation6133,
(api:"/teams/{team-id}/template",teamid: string):operation6134,
(api:"/teams/$count"):operation6135,
(api:"/teams/microsoft.graph.getAllMessages()"):operation6136,
(api:"/teamsTemplates"):operation6137,
(api:"/teamsTemplates/{teamsTemplate-id}",teamsTemplateid: string):operation6138,
(api:"/teamsTemplates/$count"):operation6139,
(api:"/teamwork"):operation6140,
(api:"/teamwork/workforceIntegrations"):operation6141,
(api:"/teamwork/workforceIntegrations/{workforceIntegration-id}",workforceIntegrationid: string):operation6142,
(api:"/teamwork/workforceIntegrations/$count"):operation6143,

(api:"/communications"):operation180,
    (api:"/communications/callRecords"):operation181,
    (api:"/communications/callRecords/{callRecord-id}",callRecordid: string):operation182,
    (api:"/communications/callRecords/{callRecord-id}/sessions",callRecordid: string):operation183,
    (api:"/communications/callRecords/{callRecord-id}/sessions/{session-id}",callRecordid: string,sessionid: string):operation184,
    (api:"/communications/callRecords/{callRecord-id}/sessions/{session-id}/segments",callRecordid: string,sessionid: string):operation185,
    (api:"/communications/callRecords/{callRecord-id}/sessions/{session-id}/segments/{segment-id}",callRecordid: string,sessionid: string,segmentid: string):operation186,
    (api:"/communications/callRecords/{callRecord-id}/sessions/{session-id}/segments/$count",callRecordid: string,sessionid: string):operation187,
    (api:"/communications/callRecords/{callRecord-id}/sessions/$count",callRecordid: string):operation188,
    (api:"/communications/callRecords/$count"):operation189,
    (api:"/communications/callRecords/microsoft.graph.callRecords.getDirectRoutingCalls(fromDateTime='{fromDateTime}',toDateTime='{toDateTime}')",fromDateTime: string,toDateTime: string):operation190,
    (api:"/communications/callRecords/microsoft.graph.callRecords.getPstnCalls(fromDateTime='{fromDateTime}',toDateTime='{toDateTime}')",fromDateTime: string,toDateTime: string):operation191,
    (api:"/communications/calls"):operation192,
    (api:"/communications/calls/{call-id}",callid: string):operation193,
    (api:"/communications/calls/{call-id}/audioRoutingGroups",callid: string):operation194,
    (api:"/communications/calls/{call-id}/audioRoutingGroups/{audioRoutingGroup-id}",callid: string,audioRoutingGroupid: string):operation195,
    (api:"/communications/calls/{call-id}/audioRoutingGroups/$count",callid: string):operation196,
    (api:"/communications/calls/{call-id}/microsoft.graph.answer",callid: string):operation197,
    (api:"/communications/calls/{call-id}/microsoft.graph.cancelMediaProcessing",callid: string):operation198,
    (api:"/communications/calls/{call-id}/microsoft.graph.changeScreenSharingRole",callid: string):operation199,
    (api:"/communications/calls/{call-id}/microsoft.graph.keepAlive",callid: string):operation200,
    (api:"/communications/calls/{call-id}/microsoft.graph.mute",callid: string):operation201,
    (api:"/communications/calls/{call-id}/microsoft.graph.playPrompt",callid: string):operation202,
    (api:"/communications/calls/{call-id}/microsoft.graph.recordResponse",callid: string):operation203,
    (api:"/communications/calls/{call-id}/microsoft.graph.redirect",callid: string):operation204,
    (api:"/communications/calls/{call-id}/microsoft.graph.reject",callid: string):operation205,
    (api:"/communications/calls/{call-id}/microsoft.graph.subscribeToTone",callid: string):operation206,
    (api:"/communications/calls/{call-id}/microsoft.graph.transfer",callid: string):operation207,
    (api:"/communications/calls/{call-id}/microsoft.graph.unmute",callid: string):operation208,
    (api:"/communications/calls/{call-id}/microsoft.graph.updateRecordingStatus",callid: string):operation209,
    (api:"/communications/calls/{call-id}/operations",callid: string):operation210,
    (api:"/communications/calls/{call-id}/operations/{commsOperation-id}",callid: string,commsOperationid: string):operation211,
    (api:"/communications/calls/{call-id}/operations/$count",callid: string):operation212,
    (api:"/communications/calls/{call-id}/participants",callid: string):operation213,
    (api:"/communications/calls/{call-id}/participants/{participant-id}",callid: string,participantid: string):operation214,
    (api:"/communications/calls/{call-id}/participants/{participant-id}/microsoft.graph.mute",callid: string,participantid: string):operation215,
    (api:"/communications/calls/{call-id}/participants/{participant-id}/microsoft.graph.startHoldMusic",callid: string,participantid: string):operation216,
    (api:"/communications/calls/{call-id}/participants/{participant-id}/microsoft.graph.stopHoldMusic",callid: string,participantid: string):operation217,
    (api:"/communications/calls/{call-id}/participants/$count",callid: string):operation218,
    (api:"/communications/calls/{call-id}/participants/microsoft.graph.invite",callid: string):operation219,
    (api:"/communications/calls/$count"):operation220,
    (api:"/communications/calls/microsoft.graph.logTeleconferenceDeviceQuality"):operation221,
    (api:"/communications/microsoft.graph.getPresencesByUserId"):operation222,
    (api:"/communications/onlineMeetings"):operation223,
    (api:"/communications/onlineMeetings/{onlineMeeting-id}",onlineMeetingid: string):operation224,
    (api:"/communications/onlineMeetings/{onlineMeeting-id}/attendanceReports",onlineMeetingid: string):operation225,
    (api:"/communications/onlineMeetings/{onlineMeeting-id}/attendanceReports/{meetingAttendanceReport-id}",onlineMeetingid: string,meetingAttendanceReportid: string):operation226,
    (api:"/communications/onlineMeetings/{onlineMeeting-id}/attendanceReports/{meetingAttendanceReport-id}/attendanceRecords",onlineMeetingid: string,meetingAttendanceReportid: string):operation227,
    (api:"/communications/onlineMeetings/{onlineMeeting-id}/attendanceReports/{meetingAttendanceReport-id}/attendanceRecords/{attendanceRecord-id}",onlineMeetingid: string,meetingAttendanceReportid: string,attendanceRecordid: string):operation228,
    (api:"/communications/onlineMeetings/{onlineMeeting-id}/attendanceReports/{meetingAttendanceReport-id}/attendanceRecords/$count",onlineMeetingid: string,meetingAttendanceReportid: string):operation229,
    (api:"/communications/onlineMeetings/{onlineMeeting-id}/attendanceReports/$count",onlineMeetingid: string):operation230,
    (api:"/communications/onlineMeetings/{onlineMeeting-id}/attendeeReport",onlineMeetingid: string):operation231,
    (api:"/communications/onlineMeetings/$count"):operation232,
    (api:"/communications/onlineMeetings/microsoft.graph.createOrGet"):operation233,
    (api:"/communications/presences"):operation234,
    (api:"/communications/presences/{presence-id}",presenceid: string):operation235,
    (api:"/communications/presences/{presence-id}/microsoft.graph.clearPresence",presenceid: string):operation236,
    (api:"/communications/presences/{presence-id}/microsoft.graph.clearUserPreferredPresence",presenceid: string):operation237,
    (api:"/communications/presences/{presence-id}/microsoft.graph.setPresence",presenceid: string):operation238,
    (api:"/communications/presences/{presence-id}/microsoft.graph.setUserPreferredPresence",presenceid: string):operation239,
    (api:"/communications/presences/$count"):operation240,

    (api:"/appCatalogs"):operation48,
    (api:"/appCatalogs/teamsApps"):operation49,
    (api:"/appCatalogs/teamsApps/{teamsApp-id}",teamsAppid: string):operation50,
    (api:"/appCatalogs/teamsApps/{teamsApp-id}/appDefinitions",teamsAppid: string):operation51,
    (api:"/appCatalogs/teamsApps/{teamsApp-id}/appDefinitions/{teamsAppDefinition-id}",teamsAppid: string,teamsAppDefinitionid: string):operation52,
    (api:"/appCatalogs/teamsApps/{teamsApp-id}/appDefinitions/{teamsAppDefinition-id}/bot",teamsAppid: string,teamsAppDefinitionid: string):operation53,
    (api:"/appCatalogs/teamsApps/{teamsApp-id}/appDefinitions/$count",teamsAppid: string):operation54,
    (api:"/appCatalogs/teamsApps/$count"):operation55,
    (api:"/chats"):operation143,
    (api:"/chats/{chat-id}",chatid: string):operation144,
    (api:"/chats/{chat-id}/installedApps",chatid: string):operation145,
    (api:"/chats/{chat-id}/installedApps/{teamsAppInstallation-id}",chatid: string,teamsAppInstallationid: string):operation146,
    (api:"/chats/{chat-id}/installedApps/{teamsAppInstallation-id}/microsoft.graph.upgrade",chatid: string,teamsAppInstallationid: string):operation147,
    (api:"/chats/{chat-id}/installedApps/{teamsAppInstallation-id}/teamsApp",chatid: string,teamsAppInstallationid: string):operation148,
    (api:"/chats/{chat-id}/installedApps/{teamsAppInstallation-id}/teamsAppDefinition",chatid: string,teamsAppInstallationid: string):operation149,
    (api:"/chats/{chat-id}/installedApps/$count",chatid: string):operation150,
    (api:"/chats/{chat-id}/members",chatid: string):operation151,
    (api:"/chats/{chat-id}/members/{conversationMember-id}",chatid: string,conversationMemberid: string):operation152,
    (api:"/chats/{chat-id}/members/$count",chatid: string):operation153,
    (api:"/chats/{chat-id}/members/microsoft.graph.add",chatid: string):operation154,
    (api:"/chats/{chat-id}/messages",chatid: string):operation155,
    (api:"/chats/{chat-id}/messages/{chatMessage-id}",chatid: string,chatMessageid: string):operation156,
    (api:"/chats/{chat-id}/messages/{chatMessage-id}/hostedContents",chatid: string,chatMessageid: string):operation157,
    (api:"/chats/{chat-id}/messages/{chatMessage-id}/hostedContents/{chatMessageHostedContent-id}",chatid: string,chatMessageid: string,chatMessageHostedContentid: string):operation158,
    (api:"/chats/{chat-id}/messages/{chatMessage-id}/hostedContents/$count",chatid: string,chatMessageid: string):operation159,
    (api:"/chats/{chat-id}/messages/{chatMessage-id}/replies",chatid: string,chatMessageid: string):operation160,
    (api:"/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}",chatid: string,chatMessageid: string,chatMessageid1: string):operation161,
    (api:"/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents",chatid: string,chatMessageid: string,chatMessageid1: string):operation162,
    (api:"/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/{chatMessageHostedContent-id}",chatid: string,chatMessageid: string,chatMessageid1: string,chatMessageHostedContentid: string):operation163,
    (api:"/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/$count",chatid: string,chatMessageid: string,chatMessageid1: string):operation164,
    (api:"/chats/{chat-id}/messages/{chatMessage-id}/replies/$count",chatid: string,chatMessageid: string):operation165,
    (api:"/chats/{chat-id}/messages/{chatMessage-id}/replies/microsoft.graph.delta()",chatid: string,chatMessageid: string):operation166,
    (api:"/chats/{chat-id}/messages/$count",chatid: string):operation167,
    (api:"/chats/{chat-id}/messages/microsoft.graph.delta()",chatid: string):operation168,
    (api:"/chats/{chat-id}/microsoft.graph.sendActivityNotification",chatid: string):operation169,
    (api:"/chats/{chat-id}/pinnedMessages",chatid: string):operation170,
    (api:"/chats/{chat-id}/pinnedMessages/{pinnedChatMessageInfo-id}",chatid: string,pinnedChatMessageInfoid: string):operation171,
    (api:"/chats/{chat-id}/pinnedMessages/{pinnedChatMessageInfo-id}/message",chatid: string,pinnedChatMessageInfoid: string):operation172,
    (api:"/chats/{chat-id}/pinnedMessages/$count",chatid: string):operation173,
    (api:"/chats/{chat-id}/tabs",chatid: string):operation174,
    (api:"/chats/{chat-id}/tabs/{teamsTab-id}",chatid: string,teamsTabid: string):operation175,
    (api:"/chats/{chat-id}/tabs/{teamsTab-id}/teamsApp",chatid: string,teamsTabid: string):operation176,
    (api:"/chats/{chat-id}/tabs/$count",chatid: string):operation177,
    (api:"/chats/$count"):operation178,
    (api:"/chats/microsoft.graph.getAllMessages()"):operation179,