import {URLOperation100, URLOperation101, URLOperation102, URLOperation103, URLOperation104, URLOperation105, URLOperation106, URLOperation107, URLOperation108, URLOperation109, URLOperation56, URLOperation57, URLOperation58, URLOperation59, URLOperation60, URLOperation61, URLOperation62, URLOperation63, URLOperation64, URLOperation65, URLOperation66, URLOperation67, URLOperation68, URLOperation69, URLOperation70, URLOperation71, URLOperation72, URLOperation73, URLOperation74, URLOperation75, URLOperation76, URLOperation77, URLOperation78, URLOperation79, URLOperation80, URLOperation81, URLOperation82, URLOperation83, URLOperation84, URLOperation85, URLOperation86, URLOperation87, URLOperation88, URLOperation89, URLOperation90, URLOperation91, URLOperation92, URLOperation93, URLOperation94, URLOperation95, URLOperation96, URLOperation97, URLOperation98, URLOperation99} from "../../lib/graphOpsModels/operations"
import { GraphApis } from "../../lib/graphAPIs";

declare module "../../lib/graphAPIs" {

    export interface GraphApis {
        (api: "/applications"): URLOperation56,
        (api: "/applications/{application-id}"): URLOperation57,
        (api: "/applications/{application-id}/createdOnBehalfOf"): URLOperation58,
        (api: "/applications/{application-id}/extensionProperties"): URLOperation59,
        (api: "/applications/{application-id}/extensionProperties/{extensionProperty-id}"): URLOperation60,
        (api: "/applications/{application-id}/extensionProperties/$count"): URLOperation61,
        (api: "/applications/{application-id}/homeRealmDiscoveryPolicies"): URLOperation62,
        (api: "/applications/{application-id}/homeRealmDiscoveryPolicies/{homeRealmDiscoveryPolicy-id}"): URLOperation63,
        (api: "/applications/{application-id}/homeRealmDiscoveryPolicies/$count"): URLOperation64,
        (api: "/applications/{application-id}/logo"): URLOperation65,
        (api: "/applications/{application-id}/microsoft.graph.addKey"): URLOperation66,
        (api: "/applications/{application-id}/microsoft.graph.addPassword"): URLOperation67,
        (api: "/applications/{application-id}/microsoft.graph.checkMemberGroups"): URLOperation68,
        (api: "/applications/{application-id}/microsoft.graph.checkMemberObjects"): URLOperation69,
        (api: "/applications/{application-id}/microsoft.graph.getMemberGroups"): URLOperation70,
        (api: "/applications/{application-id}/microsoft.graph.getMemberObjects"): URLOperation71,
        (api: "/applications/{application-id}/microsoft.graph.removeKey"): URLOperation72,
        (api: "/applications/{application-id}/microsoft.graph.removePassword"): URLOperation73,
        (api: "/applications/{application-id}/microsoft.graph.restore"): URLOperation74,
        (api: "/applications/{application-id}/microsoft.graph.setVerifiedPublisher"): URLOperation75,
        (api: "/applications/{application-id}/microsoft.graph.unsetVerifiedPublisher"): URLOperation76,
        (api: "/applications/{application-id}/owners"): URLOperation77,
        (api: "/applications/{application-id}/owners/{directoryObject-id}/$ref"): URLOperation78,
        (api: "/applications/{application-id}/owners/{directoryObject-id}/microsoft.graph.appRoleAssignment"): URLOperation79,
        (api: "/applications/{application-id}/owners/{directoryObject-id}/microsoft.graph.endpoint"): URLOperation80,
        (api: "/applications/{application-id}/owners/{directoryObject-id}/microsoft.graph.servicePrincipal"): URLOperation81,
        (api: "/applications/{application-id}/owners/{directoryObject-id}/microsoft.graph.user"): URLOperation82,
        (api: "/applications/{application-id}/owners/$count"): URLOperation83,
        (api: "/applications/{application-id}/owners/$ref"): URLOperation84,
        (api: "/applications/{application-id}/owners/microsoft.graph.appRoleAssignment"): URLOperation85,
        (api: "/applications/{application-id}/owners/microsoft.graph.appRoleAssignment/$count"): URLOperation86,
        (api: "/applications/{application-id}/owners/microsoft.graph.endpoint"): URLOperation87,
        (api: "/applications/{application-id}/owners/microsoft.graph.endpoint/$count"): URLOperation88,
        (api: "/applications/{application-id}/owners/microsoft.graph.servicePrincipal"): URLOperation89,
        (api: "/applications/{application-id}/owners/microsoft.graph.servicePrincipal/$count"): URLOperation90,
        (api: "/applications/{application-id}/owners/microsoft.graph.user"): URLOperation91,
        (api: "/applications/{application-id}/owners/microsoft.graph.user/$count"): URLOperation92,
        (api: "/applications/{application-id}/tokenIssuancePolicies"): URLOperation93,
        (api: "/applications/{application-id}/tokenIssuancePolicies/{tokenIssuancePolicy-id}/$ref"): URLOperation94,
        (api: "/applications/{application-id}/tokenIssuancePolicies/$count"): URLOperation95,
        (api: "/applications/{application-id}/tokenIssuancePolicies/$ref"): URLOperation96,
        (api: "/applications/{application-id}/tokenLifetimePolicies"): URLOperation97,
        (api: "/applications/{application-id}/tokenLifetimePolicies/{tokenLifetimePolicy-id}/$ref"): URLOperation98,
        (api: "/applications/{application-id}/tokenLifetimePolicies/$count"): URLOperation99,
        (api: "/applications/{application-id}/tokenLifetimePolicies/$ref"): URLOperation100,
        (api: "/applications/$count"): URLOperation101,
        (api: "/applications/microsoft.graph.delta()"): URLOperation102,
        (api: "/applications/microsoft.graph.getAvailableExtensionProperties"): URLOperation103,
        (api: "/applications/microsoft.graph.getByIds"): URLOperation104,
        (api: "/applications/microsoft.graph.validateProperties"): URLOperation105,
        (api: "/applicationTemplates"): URLOperation106,
        (api: "/applicationTemplates/{applicationTemplate-id}"): URLOperation107,
        (api: "/applicationTemplates/{applicationTemplate-id}/microsoft.graph.instantiate"): URLOperation108,
        (api: "/applicationTemplates/$count"): URLOperation109,
    }

}